


=== Title: The Evolution of Humanity - (Snippet from Alba Weinman 181 )

=== Date Transcribed: December 1st, 2017

=== Original Source Reference:

181 Alba Weinman - The New Earth and the Evolution of Humanity (Part 2),
Published on Nov 29, 2017, Link: https://youtu.be/1zNRhDpy1dY

=== The Evolution of Humanity - 181snippetalbaweinman.adoc


When the veils are lifted +
    you will be given the opportunity to surrender to source.... +
 +
[ What would someone experience when the veil is lifted? ] +
 +
When the veil is lifted, all of you, will have, +
    the power to manifest anything. +
 +
To go anywhere, +
    in an instant. +

Most of you will fall into your unfulfilled expectations from the physical. +
 +
Most of you will be...  +
 +
    Re-creating... Manifesting...  +
 +
        This body is very clinched tight.  +
 +
When the veil is lifted u will manifest, +
 +
    what you've always dreamed of, +
 +
        what you seek daily. +
 +
Most of u are wrapped around fear, +
 +
    And seek to be noticed, loved. +
 +
        Seek to be safe from the sensation of judgment. +
 +
Judgment lives and rules the day in your world. +
 +
    When u dream at night, +
 +
        You create. +
 +
    Each one of u manifests. +
 +
This is what u will do when the veil is lifted. +
 +
    [ so are we practicing at night? ] +
 +
Most no - most are like children, +
 +
Very few in this reality, +
 +
Recall how to communicate, +
 +
    how to connect, +
 +
        most of you are walking blind.  +
 +
 +

_*When the veil is lifted...*_  +
 +
    You will have the power to commune with the dead, +
 +
        They will be before you. +
 +
Many lost souls, fearful, +
 +
    Who have created there own universe around them, +
 +
        They did not transition, +
 +
            and you will be frightened, +
 +
                and your first instinct will be to wrap yourself in fear, +
 +
        For some, +
 +
            the sense of security will be, +
 +
                there home, +
 +
        And you will re-create your home, +
 +
            maybe your bed, or Jesus, ... +
 +
                you will have the ability to manifest, +
 +
                    Anything. +
 +
Many will be suicidal to this new ability, +
 +
    to manifest +
 +
        that is why now... +
 +
            you should... +
 +
                be +
 +
                    developing +
 +
    your potential to connect and commune   +
 +
        with the divine. +
 +
_*When the veil is lifted,*_ +
 +
    many human beings, +
 +
        will, +
 +
             be shouting... +
 +
They all wait until the last possible moment, +
 +
    and they will be preying in unison. +
 +
        and at that moment... +
 +
            _*they will find themselves.*_ +
 +
     [ so there is hope? ] +
 +
_*humanity is on the brink....*_ +
 +
    There is another world, +
 +
        that depends on you now. +
 +
    Just as there is a group....of beings +
 +
        that are nudging us forward +
 +
            to evolve. +
 +
_*Humanity can fall, it is not a given*_. +
 +
    _*Humanity is meant to evolve.*_ +
 +
    [ what does this new earth look like ? ] +
 +
*LOVE RULES THE DAY* +
 +
    Fear Rules This Earth +
 +
        If you are able to make this jump, +
 +
            *Find a way to evolve,* +
 +
This Earth is there now. +
 +
    It has happened. +
 +
        And it will happen again. +
 +
Your energy comes from the sun and the divine spark, +
 +
        _*The One.*_ +
 +
You won't consume food the way you do now. +
 +
    Life will be much simpler +
 +
And communication will be instantaneous. +
 +
    [ what will we look like? ] +
 +
Glowing.  +
 +
Our bodies where just created to house our souls. +

    Imagine an intelligent machine... +

This place here... +
 +
    is such an interesting experiment. +
 +
        The bodies here are all sick... +
 +
In the new earth everything is known... +
 +
    even plants and animals matter, +
 +
        all the cells and life force +
 +
            that makes up everything is known. +
 +
Communication is instantaneous. +
 +
    It is a place to strive for, +
 +
        it is there now. +
 +
Infinite number of potentials, +
 +
    This dimension, this time line, +
 +
        Our thoughts are creating this space we are in now, +
 +
            Many of u are aware now u can feel it, +
 +
        but, +
 +
    You are still blind to what u need to know +
 +
        _*to survive this moment we are racing to.*_ +
 +
You must learn to clear the clutter form your heads. +
 +
    Because this new earth u are seeking... +
 +
        The amount of energy u have put forth to learn, +
 +
            you are now being given, +
 +
                what i am here to tell u,  +
 +
                    you must learn to commune with your higher self. +
 +
Try to imagine an infinite number of yourself s, +
 +
    you have created many potentials of yourself s, +
 +
        when u decided to incarnate yourself to learn, +
 +
            you do not just come to this particular experience, +
 +
        to where u are now... +
 +
            its a limiting way of thinking... +
 +
If u really want to know what it is like to be a human +
 +
    being or would you limit yourself to this time and place, +
 +
       only speaking one language, one type of human beings, +
 +
Would you not want to experience a multitudes of races, experiences, +
 +
    emotions.
 +
This is what you have created, you need to find source, +
 +
    _*The only way to achieve the union....*_ +
 +
        _*Is to find this energy that is in each one of you.*_ +
 +
*This moment is real.* +
 +
    _*It is real.*_ +
 +
        *It will not wait for you.* +
 +
             Many will miss it. +
 +
You will not miss the event, +
 +
    It's weather or not u can find... +
 +
        this new earth as u choose to call it, +
 +
what happens... +
 +
    you will stay here. +
 +
        and pick up the peaces, +
 +
_*This world now around you is collapsing,*_ +
 +
    _*Earth will attempt to swipe u away.*_ +
 +
        It will not be a very habitable environment... +
 +
   [ more specific by swipe away?]  +
 +
Earth is a living being +
 +
    Would your body not do the same if u had a virus +
 +
        Inside that was affecting the function +
 +
            that influenced your potential to evolve and grow. +
 +
        You would look for a cure. +
 +
            You would want to eradicate this...this..intrusion. +
 +
 +
    Earth is doing this now, +
 +
        Its beginning +
 +
Just as humanity is beginning to work against it, the light and the dark, +
 +
    I'm here to persuade you... +
 +
        because I am you.... And you are me. +
 +
We are one in the same. +
 +
    And my gift to you now here in this space, +
 +
       Is to tell you... +
 +
           That this moment is near... +
 +
               you can feel it.... +
 +
                   everyone senses... +
 +
    Its a choice we are all making. +
 +
 +
[ when is this going to happen ? ] +
 +
_*Man is creating this moment you.*_ +
 +
Difficult to pinpoint the beginning and end of the storm. +
 +
A typhoon that's approaching +
 +
It seems as tho the sun is out... +
 +
    That there is calm before the storm... +
 +
The win begins to rise.... +
 +
    and u still tell yourself... +
 +
This is just the wind... +
 +
    I'm not afraid of the wind... +
 +
Oh there is a war but this is a different kind of war +
 +
    I'm not afraid of this... +
 +
        This is happening now. +
 +
 +

This will be the moment of your greatest fears... Cause that is how +
 +
    you have manifested it to be... +
 +
_*The moment of your most frightened experience that u can imagine*_ +
 +
    _*Is what will nudge you to diving deep within yourself....*_ +
 +
        *That's when u know....* +
 +
            *Its time to evolve or not.* +
 +
                *This time it is here now.* +
 +
 +
    [ same for everyone or different for each person ] +
 +
Each person has different view of God and hell. +
 +
    This being, Gary, is unique to his own creation. +
 +
 +
_*You must square the circle*_  +
 +
    [ what does that mean? ]   +
 +
_*You must make the impossible,*_ +
 +
        _*possible.*_ +
 +
_*We can not do this for you,*_ +
 +
    _*It has always been this way,*_ +
 +
        _*And it will continue to be this way..*_ +
 +
            _*You must find a way to evolve.*_ +
 +
 +
    [ thank you. ] +
 +
 +
 +
*The Message is LOVE - Surrender to LOVE* +
 +
    *Sounds easy but everyone is afraid to bare there love* +

 +
 +
 +
 +

 



