

== a_whisper_in_your_dream.adoc
<Disappearance of The Universe @ By Gary Renard>


----

"[Gary Renard's Disappearance of the Universe shines light on the concepts in a Coarse In Miracles.

 In one hundred years the Course In Miracles concepts will become known as the true teachings of Jesus.

 Events occurred from December 1992 through December of 2001.

 Three participants were - Gary and Arten and Pursah (Ascended Masters)

 The attitudes of Arten and Pursah were: gentleness, humor, humility, and love.]"

----


"There are those who have reached God directly, retaining no trace of worldly limits remembering their own identity perfectly.  These might be called the Teachers of teachers because, although they are no longer visible, their image can yet be called upon.  And they will appear when and where it is helpful for them to do so.  To those to whom such appearances would be frightening, they give their ideas.  No one can call on them in vein.  Nor is there anyone of whom they are unaware." --- A Course In Miracles via The Disappearance of The Universe.


"There are those who have reached God directly, retaining no trace of worldly limits remembering their own identity perfectly.  These might be called the Teachers of teachers because, although they are no longer visible, their image can yet be called upon.  And they will appear when and where it is helpful for them to do so.  To those to whom such appearances would be frightening, they give their ideas.  No one can call on them in vein.  Nor is there anyone of whom they are unaware." --- A Course In Miracles via The Disappearance of The Universe.

* "We are appearing to you as symbols whose words will help facilitate the disappearance of the universe.

* To correct something usually means you fix it up and keep it.  When the false universe is finished being corrected by the Holy Spirit, it will no longer appear to exist.

* The world needs another religion like it needs another hole in the ozone layer.

* Your good times in the world are good only in comparison to the bad times.  You will eventually learn that it's all a trick.

----

"Thinking positively, being "in the now", saying prayers, affirmations, denying negative thoughts... [help some] cannot release whats locked in the unconscious mind...

Unconscious Mind is shared by a sick thought system shared by the collective and individual level by everyone who comes to the false universe.

This will remain the case until your thoughts are examined, correctly forgiven, released to the Holly Spirit, and replaced with his thinking instead."

----


----

"The world is merely acting out a symbolic scenario that each one here agreed to participate in before they ever appeared to arrive.

J can help you examine the subconscious mind.

If you want to go home J is outside the door of the asylum._ _You keep trying to drag him back in.

----


* How would you feel if someone who was as dead as a door nail stopped by to have a chat with you?

* How much success or money you get has nothing whatsoever to do with how spiritually enlightened you are.

* The nonsensical tragedy of duality is considered to be normal by all modern societies, which are themselves as mad as a hatter.

* A jet liner is always going off course, but through constant correction it arrives at it's destination.  So will you arrive at yours."


----

"Arden: As I said, J was neither judgmental or a reactionary, and our brief outline of non-dualism should have given you the idea that he would not compromise on this logic:

If nothing is outside of your mind, then to judge it is to grant it power over you and to not judge it is to not grant it power over you.  This certainly contributes to the end of your suffering.

Pure non-dualism relinquishes anything that is not God.  

Like From Like Principle - Anything coming from God must be like him. Anything coming from him must be exactly like him.

If God is perfect and eternal than anything he creates is perfect and eternal.

Humility is the way - not a false humility that says you are inadequate, but a real humility that says God is your only source."

----

* For God to create the imperfect must either mean that He was imperfect or that He deliberately made those who were so they could screw up, be punished by him and suffer here on psycho planet.

----

"A fearful image of God rather than a loving one.

The Kingdom of God is present but unseen by people.

All right. Your saying that J saw people as being the same as him and God - unlimited and perfect.  All other characteristics we put onto other people or onto God are really are own unconscious beliefs about ourselves.

Monotheism originated with Akhnation in ancient Egypt.

...his mind had been returned to the Holy Spirit where it belonged.  You took it and you have to give it back.  And I've got a message for you: You'll never really be happy until you do."

----

* J's _*peace*_ and _*unilateral love*_ were so total that sometimes people couldn't stand it and had to look away.

* Humans have built and destroyed many advanced civilizations on this planet.  The same process is being repeated as we speak.

* Even on the level of form.  Arabs and Jews, like Serbs and Muslims, are basically the same - which shows you how far people will go to be different.

* You think the universe is evolving... But it's really _*just spinning it's wheels*_, _*repeating the same pattern over and over in different forms.*_

* I got my head cut off in India.  When you're in a body you just never know what kind of a day it's going to be.

* You must be vigilant only for God. This state of mind does not come all at once; it takes a lot of practice.  You don't learn anything worth while overnight.

----

"I am the one who comes from what is whole. I was given from things of my Father.  Therefore, I say that if one is whole, one will be filled with light, but if one is divided, one will be filled with darkness.

Whoever drinks from my mouth shall become like me, I myself shall become that person, and the hidden things be revealed to that person.

I shall choose you, one from a thousand and two from ten thousand, and they shall stand as a single one.

The disciples said to him, "When will the Kingdom come?"  He said, "It will not come by watching for it. It will not be said, "Behold here," or "Behold there.", rather, the Kingdom of the Father is spread out upon the earth, and people do not see it.

Heaven does not exist within the realm of perception, but in the genuine form of Life that you will eventually become completely aware of it."

----

* _*Like the caterpillar becomes the butterfly, you will become Christ - _*and be one with all True Creation.*_ "













