

=== Title: "Aliens Confirm Disclosure"

=== Date: August 5th 2018

=== Description: "General recollection" of conversation with Aliens.


Questions to the Aliens through a human telepath went as followed:

* Question 1 - Human:

General Question posed on clarifing all the different beings that built earth.For example, in deep hypnosis regression they talk about some beings create the green and other beings may be water or wind.  Can you clarify?  Are there thousands of beings involved in making earth?

Alien Answer:

The Creator or God created earth but many different types of beings altered earth after that.  Maybe 500 to 1000 different beings.  Note: This is why they are very sad when they see what the humans are doing to earth.  Imagine you did all this work to create earth and someone came and tore down all the trees and forest... as you can see it would be very upsetting.

Note: Clarified there are really no "Demon Being" per say, just negative and positive beings just as you have negative and positive humans.


Question 2 - Human:

* Is Emery Smith's story about a genetically created Moss-Being accurate or is it just a story? (or disinformation).


Alien Answer:

You mean the spy-plant being.  Yes, but there are many, many beings getting created and it is not a good thing to create beings and kill them.  It is very, very sad and humans should not be doing this.  Remember these beings also have a soul, and animals have a soul as well.


Contemplations:  

Makes you wonder if this means you could have a person remembering a past life as one of these beings and remembering the bad experiences. 



* Question 3 - Human:

Is Corey Goode's story about 1 million humans being abducted or killed a year accurate?  Can you elaborate if this is true or not?


Alien Answer:

(Didn't directly confirm the number 1 million)

Yes, Initially the exchange program was meant to do good but things went off track.  We are deeply, deeply, sorry for this and we are working very hard to correct this.  Although the mission was supposed to be friendly there where negative aliens just like there are negative humans and innocent soldiers and humans did died.  

Note: I was commenting regarding to a friendly exchange mission in space but the aliens also seemed to imply the events or took place on earth as well.


* Question 4 - Human

It has been said that Aliens are on earth and have the ability to cloak or hide themselves using a "projection" type higher mental procedure that intertwines at the mind levels.  Is there any procedure or method you give inform me of so I could see who the aliens Are?


Alien Answer:

No, but some people who have achieved a level of high ascension have developed the ability or gained the ability to see who the aliens really are... Unfornately, most of these people are labeled crazy and sent to mental institutions.  Also the goverment may or does have a device that can measure the "frequency" of a body to determine if it is Alien.  Again, no procedure or method to give you to see the aliens.



In Conclusion:

These where some of the questions asked to a telepathic human who relayed the answers from the aliens.  No Aliens where seen - All Done Telepathically.  

* The accuracy of this information is undetermined.  Hard to guess if it is 99.9 percent accurate or 90%, or 80% or 50% accurate.

The answers seem to bluntly confirm Emery Smith's and Corey Goode's information but there is no guarntee how accurate this information is.  The information seems to very sad and moralistic as well.










