=== How Big Would A Meteorite Have To Be To Wipe Out All Human Life?
=== by Daniel Engber
=== Dated February 26, 2015
=== WebSite: Popular Science


=== Short answer: 60 miles wide, give or take

When it comes to meteorites, the bigger they are, the more havoc they generally wreak. In 1997, University of Colorado geoscientist Brian Toon and colleagues predicted the aftermath of meteorite impacts of various sizes. They found that a space rock half a mile wide would produce an explosion that releases the energy equivalent of up to 100,000 million tons (Mt) of TNT. That’s enough to cause widespread blast damage and earthquakes, but nothing too out of line with many natural disasters in the modern age. Once a collision exceeds the 100,000 Mt threshold, you’re looking at a catastrophe larger than any in human history. A meteorite a mile in diameter might send enough pulverized rock into the stratosphere to block out sunlight and cause global cooling.

The object that killed off the dinosaurs was probably seven or eight miles wide, says Jay Melosh, a planetary physicist at Purdue University. Its impact would have ejected a dust plume that spread clear around the planet and rained blazing-hot on to forests, igniting them. “The dinosaurs probably broiled to death,” he says.

Such a collision today would kill billions of people. Those who didn’t perish in the initial blast or the fires that followed would face long odds of finding sustenance. “People are going to starve to death,” Toon says. Still, a few would likely weather the apocalyptic storm. “Probably some fishermen in Costa Rica,” he offers. “People near the oceans who managed to hide out and fish when the fires started.”

For a collision to obliterate the human race altogether, Toon estimates it would take a 60-mile-wide meteorite. He says, “That would incinerate everybody.”

This article was originally published in the February 2015 issue of Popular Science.

Have a question? Tweet your science questions and quandaries to @PopSci with the hashtag #AskAnything, or email us at AskAnything@popsci.com.




