=== Title: A Quantum Theory Proves Consciousness Moves To Another Universe After Death
=== WebSite: http://www.theearthchild.co.za/quantum-theory-consciousness-moves-to-another-universe-after-death/
=== By: Dr. Robert Lanza

=== Introduction

A book titled “Biocentrism: How Life and Consciousness Are the Keys to Understanding the Nature of the Universe” has stirred up the Internet, because it contained a notion that life does not end when the body dies, and it can last forever.

The author of this publication, scientist Dr. Robert Lanza who was voted the 3rd most important scientist alive by the NY Times, has no doubts that this is possible.

=== 1. Beyond Time And Space

Lanza is an expert in regenerative medicine and scientific director of Advanced Cell Technology Company. Before he has been known for his extensive research which dealt with stem cells, he was also famous for several successful experiments on cloning endangered animal species.

But not so long ago, the scientist became involved with physics, quantum mechanics and astrophysics. This explosive mixture has given birth to the new theory of biocentrism, which the professor has been preaching ever since. Biocentrism teaches that life and consciousness are fundamental to the universe. It is consciousness that creates the material universe, not the other way around.

Lanza points to the structure of the universe itself, and that the laws, forces, and constants of the universe appear to be fine-tuned for life, implying intelligence existed prior to matter. He also claims that space and time are not objects or things, but rather tools of our animal understanding. Lanza says that we carry space and time around with us “like turtles with shells.” meaning that when the shell comes off (space and time), we still exist.

The theory implies that death of consciousness simply does not exist. It only exists as a thought because people identify themselves with their body. They believe that the body is going to perish, sooner or later, thinking their consciousness will disappear too. If the body generates consciousness, then consciousness dies when the body dies. But if the body receives consciousness in the same way that a cable box receives satellite signals, then of course consciousness does not end at the death of the physical vehicle. In fact, consciousness exists outside of constraints of time and space. It is able to be anywhere: in the human body and outside of it. In other words, it is non-local in the same sense that quantum objects are non-local.

Lanza also believes that multiple universes can exist simultaneously. In one universe, the body can be dead. And in another it continues to exist, absorbing consciousness which migrated into this universe. This means that a dead person while traveling through the same tunnel ends up not in hell or in heaven, but in a similar world he or she once inhabited, but this time alive. And so on, infinitely. It’s almost like a cosmic Russian doll afterlife effect.

=== 2. Multiple Worlds

This hope-instilling, but extremely controversial theory by Lanza has many unwitting supporters, not just mere mortals who want to live forever, but also some well-known scientists. These are the physicists and astrophysicists who tend to agree with existence of parallel worlds and who suggest the possibility of multiple universes. Multiverse (multi-universe) is a so-called scientific concept, which they defend. They believe that no physical laws exist which would prohibit the existence of parallel worlds.

The first one was a science fiction writer H.G. Wells who proclaimed in 1895 in his story “The Door in the Wall”. And after 62 years, this idea was developed by Dr. Hugh Everett in his graduate thesis at the Princeton University. It basically posits that at any given moment the universe divides into countless similar instances. And the next moment, these “newborn” universes split in a similar fashion. In some of these worlds you may be present: reading this article in one universe, or watching TV in another.

The triggering factor for these multiplyingworlds is our actions, explained Everett. If we make some choices, instantly one universe splits into two with different versions of outcomes.

In the 1980s, Andrei Linde, scientist from the Lebedev’s Institute of physics, developed the theory of multiple universes. He is now a professor at Stanford University. Linde explained: Space consists of many inflating spheres, which give rise to similar spheres, and those, in turn, produce spheres in even greater numbers, and so on to infinity. In the universe, they are spaced apart. They are not aware of each other’s existence. But they represent parts of the same physical universe.

The fact that our universe is not alone is supported by data received from the Planck space telescope. Using the data, scientists have created the most accurate map of the microwave background, the so-called cosmic relic background radiation, which has remained since the inception of our universe. They also found that the universe has a lot of dark recesses represented by some holes and extensive gaps.

Theoretical physicist Laura Mersini-Houghton from the North Carolina University with her colleagues argue: the anomalies of the microwave background exist due to the fact that our universe is influenced by other universes existing nearby. And holes and gaps are a direct result of attacks on us by neighboring universes.

=== 3. Soul

So, there is abundance of places or other universes where our soul could migrate after death, according to the theory of neo-biocentrism. But does the soul exist? Is there any scientific theory of consciousness that could accommodate such a claim? According to Dr. Stuart Hameroff, a near-death experience happens when the quantum information that inhabits the nervous system leaves the body and dissipates into the universe. Contrary to materialistic accounts of consciousness, Dr. Hameroff offers an alternative explanation of consciousness that can perhaps appeal to both the rational scientific mind and personal intuitions.

Consciousness resides, according to Stuart and British physicist Sir Roger Penrose, in the microtubules of the brain cells, which are the primary sites of quantum processing. Upon death, this information is released from your body, meaning that your consciousness goes with it. They have argued that our experience of consciousness is the result of quantum gravity effects in these microtubules, a theory which they dubbed orchestrated objective reduction (Orch-OR).

Consciousness, or at least proto-consciousness is theorized by them to be a fundamental property of the universe, present even at the first moment of the universe during the Big Bang. “In one such scheme proto-conscious experience is a basic property of physical reality accessible to a quantum process associated with brain activity.”

Our souls are in fact constructed from the very fabric of the universe – and may have existed since the beginning of time. Our brains are just receivers and amplifiers for the proto-consciousness that is intrinsic to the fabric of space-time. So is there really a part of your consciousness that is non-material and will live on after the death of your physical body?

Dr Hameroff told the Science Channel’s Through the Wormhole documentary: “Let’s say the heart stops beating, the blood stops flowing, the microtubules lose their quantum state. The quantum information within the microtubules is not destroyed, it can’t be destroyed, it just distributes and dissipates to the universe at large”. Robert Lanza would add here that not only does it exist in the universe, it exists perhaps in another universe. If the patient is resuscitated, revived, this quantum information can go back into the microtubules and the patient says “I had a near death experience”

He adds: “If they’re not revived, and the patient dies, it’s possible that this quantum information can exist outside the body, perhaps indefinitely, as a soul.”

This account of quantum consciousness explains things like near-death experiences, astral projection, out of body experiences, and even reincarnation without needing to appeal to religious ideology. The energy of your consciousness potentially gets recycled back into a different body at some point, and in the mean time it exists outside of the physical body on some other level of reality, and possibly in another universe.


=== Short Summary

1. Dr. Robert Lanza wrote a book called, "Biocentrism: How Life and Consciousness Are the Keys to Understanding the Nature of the Universe".

2. The book contains the idea that "life does not end when the body dies, and it can last forever."

3. Dr. Lanza's main areas of study are physics, quantum mechanics and astrophysics and this has given birth to a new theory of biocentrism.

4. Biocentrism teaches that life and consciousness are fundamental to the universe and it is consciosuness that creates the material universe.

5. "intelligence existed prior to matter"

6. "we carry space and time around with us "like turtles with shells" meaning that when the shell comse off (space and time), we still exist.

7. The theory implies that death of consciousness imply does not exist.

8. Consciousness exists outside of constraints of time and space.

9. Plank space telescope suggests the universe is not alone - multi-verse.

10. Our SOUL may migrate to other places after death.

11. Consciousness resides, according to Stuart and Si Roger Penrose in 
microtubles of the brain cells. 

12. *Objective Reduction (Orch-OR)* is the theory that consciousness is the result of quantum gravity effects in these microtubules.

13. *Proto-Consciousness* is a theory that it is a fundamental property of the universe and was present even at the first moment of the universe and is a basic proeprty of physical reality. 

14. Souls are constructed of the fabric of the universe and may have existed since the beginning of time.  And may be non-material and exist after.

15. Quantum ConSciousness

=== Short Opinion Analysis

This sounds very similar to "The Tibetan Book of the Dead" and reaffirms that Science and Religion could be leading to the same destination?




