


=== Title: "Astral Projection and Hypnosis Research in the 80s"

=== By: Caroline Haskins

=== Date: July 22, 2017, 10:00am

=== Source Link: https://motherboard.vice.com/en_us/article/pad4a9/the-us-army-funded-astral-projection-and-hypnosis-research-in-the-80s




* This is a real-life X-File.  Image of a skull title *Consciusness Energy Grid*

"Human consciousness is nothing but an intersection of energy planes that forms a hologram able to travel through spacetime—across the universe, and into the past, present, and future. 

I read about this idea in a CIA document about the US Army. Yes, the US Army. The institution that painstakingly crafts an image of commitment to pragmatic and logical objectives. When I was reading through the documents, I was certainly a bit surprised.

According to the declassified CIA documents that I read, the US Army was extremely interested in psychic experimentation. From the late 1970s into the 80s, it even paid for intelligence officers to go on weeklong excursions to an out-of-the-way institute specializing in out-of-body experiences and astral projection.

The documents were declassified as early as 2001, but they caught my eye when they appeared in a /r/conspiracy post earlier this month. The psychic experimentation program, which was called "Project Center Lane," interviewed Army intelligence officers in order "to determine attitudes about the possible use of psychoenergetic phenomena in the intelligence field," according to the declassified CIA document from 1984. 

As a huge fan of The X-Files, I couldn't resist reading as much as I could about Project Center Lane, which looks like it could have appeared on the show.

In June 1983, Army Commander Wayne M. McDonnell was asked to give his commander an assessment of the psychic services provided by the Monroe Institute, a non-profit organization focused on treatments designed to expand a person's consciousness. The Monroe Institute is known for its patented "Hemi-Sync" technology, which uses audio to synchronize the brainwaves on the left and right sides of the brain. According to the organization's website, this makes the brain vulnerable to hypnosis. McDonnell himself had completed the seven-day psychic program the month prior at the institute, which is lodged in the middle of Virginia's Blue Ridge Mountains in a town called Faber, about 30 miles east of Charlottesville. 

 McDonnell's assessment, collected from his experience at the secluded institute, formed the basis of a 29-page Army document that featured detailed explanations of hypnosis, holograms, and out-of-body experiences. The document placed these phenomena in the context of larger ideas of consciousness, energy, space-time, quantum subatomic particles, and so-called astral projection, a practice that aims to transport consciousness around a metaphysical plane—a central idea in McDonnell's assessment. 

McDonnell cited a metaphor penned by Monroe Institute employee Melissa Jager in order to illustrate the nature of hypnosis. The metaphor says that a normal state of consciousness is like a lamp, which emits light in a "chaotic, incoherent way." However, a hypnotized state of consciousness is said to be like a laser beam, whose thoughts and energy are focused like a "disciplined stream" of light.

* Left Hemisphere Consciousness Grid - Acts like the Mind's computer software to reduce input from right hemisphere to verbal symbols and concepts.

Right Hemisphere Consciousness Grid - Reduces three dimension holographic image to two dimensional go/no go

"Intuitional insights of not only personal but of a practical and professional nature would seem to be within bounds of reasonable expectations," McDonnell wrote, in reference to parapsychology.

In other words, Commander McDonnell concluded, hypnosis and astral projection are worth the Army's while.

Officers accepted into Project Center Lane underwent hypnosis and practiced reaching the so-called "astral plane," with the goal of learning foreign languages and undergoing what the documents only refer to as "habit control training." 

 According to one of the declassified Army files, 251 Army intelligence candidates were selected for the first year of experimentation. Of those candidates, 117 were interviewed under the impression that they were taking a survey. The document gives no specifics about the survey itself, but does indicates that the interviewer asked fairly direct questions about "psychoenergetics."

"Individuals who had objections to the military use of psychoenergetics were not considered for the final selection," the document reads. "Additionally, individuals who displayed an unreasonable enthusiasm for psychoenergetics, occult fanatics and mystical zealots were not considered for final selection."

Between 30 and 35 of the original 251 candidates were said to have "desired" traits, such as open-mindedness and intelligence, that made them suited for the program. 

Intelligence officers who were accepted to the program were sent to the Monroe Institute. Officers would then listen to the "Hemi-Sync" audio. After this, one of the institute's research associates would guide intelligence officers into the astral plane, a psychic space in which the institute said that the officers supposedly could heighten their sensory experiences, heal their bodies, travel into the past or future, or even solve real-world dilemmas without the restraints of a physical body.

Another technique known as "remote viewing" was also employed upon government employees of an unknown agency, according to a declassified document from 1982. The document doesn't specifically mention the Army or the Monroe Institute, but it precisely follows the description of remote viewing which was explained in detail in a 1983 document that explicitly mentions the facility. 

The goal of the psychic session was to make the subject remotely view Mars in the year 1 million B.C. According to the transcript, an interviewer read coordinates and verbal cues to a subject, who claimed to see dust storms, alien structures, and even an ancient alien race. 

"Very tall, again, very large people," the unidentified subject said, according to the transcript. "But they're thin. They look thin because of their height. And they dress like—oh, hell—it's like a real light silk. But it's not flowing type of clothing. It's cut to fit. They're ancient people. They're dying. It's past their time or age. They're very philosophic about it. They're looking for a way to survive and they just can't." 

I reached out to the US Army Intelligence and Security Command, the specific intelligence unit that had a relationship with the Monroe Institute, for any information about its use of Hemi-Sync technology. Ron Young, an INSCOM representative, told me in an email that after checking with the unit's division at Fort Meade, Maryland, "no records are on file for the technology you request information on." 

Young pointed out that the US Army Operational Group (AOG), featured in the heading of a 1983 document, was disbanded in 1995, after which all files relevant to the Monroe Institute were transferred to whichever agency absorbed the AOG. (The files were later released under a Freedom of Information Act request.) Young couldn't tell me which agency absorbed the AOG.

I contacted the CIA about which agency absorbed the AOG, or how the CIA came into the possession of documents related to the Monroe Institute. The agency didn't have either piece of information. 

I reached out to The Monroe Institute repeatedly for comment, but I was always referred to Executive Director Nancy McMoneagle, who was never available to speak with me. However, its website openly speaks about its previous relationship with the US Army. 

Ray Waldkoetter, who is described as a "personnel management analyst," wrote an article for the 1991 Hemi-Sync® Journal reviewing the Army's uses of Hemi-Sync technology, which is available on the Monroe Institute's website. He wrote that the Army used Hemi-Sync technology for stress reduction, psychological counseling, and enhanced learning abilities of various levels of personnel, as well as training for people seeking officer-level positions. 

"Several intensive experiences in Army military training programs have demonstrated positive results using the Hemi-Sync technology," Waldkoetter wrote.

This is hardly the first time the Army and US military at large experimented with paranormal phenomena. The branch has been known to dabble in witchcraft, psychic visions, excessive LSD, and hypnosis as an interrogation method. In 1972, the government even attempted a psychic probe of the Jupiter just months before Pioneer 10 retrieved the first scientific data and photographs of the gaseous planet. While we don't know which government agency conducted this probe, the document was eventually declassified by the NSA.

It's unclear when exactly the Army's collaboration with the Monroe Institute came to an end, but in a Wall Street Journal article from 1994 (paywall), former INSCOM director Albert Stubblebine confirmed that the Army indeed sent intelligence officers to the Institute during the 1980s. The CIA report outlining some of these techniques is also dated January 1984.

If you want to try your hand at projecting your consciousness to a higher plane, The Monroe Institute is still operating and selling its Hemi-Sync program today. Either way, you can rest assured that the wildest conspiracy theory you can imagine is actually true. 

Article Links:

https://www.cia.gov/library/readingroom/docs/CIA-RDP96-00792R000100140041-7.pdf

https://www.monroeinstitute.org/catalog/hemi-sync%C2%AE

https://www.cia.gov/library/readingroom/docs/CIA-RDP96-00788R001700210016-5.pdf







