


Title: "Want To Become A Successful Writer? You need To Do These 2 Things (daily)

By: Nicolas Cole

Dated: Dec 28

Source Link: https://medium.com/@nicolascole77/want-to-become-a-successful-writer-you-need-to-do-these-2-things-daily-83152fd61b33


_If you want to become a writer, you have to write._

=== I am going to continue saying this, like a mantra, because it is truly the most fundamental habit required in order to write well.

Back before I set my sights on becoming a professional writer, I would write short stories here and there, some poetry in my journal late at night.

I would write a blog on my website and then delete it, write another one a few weeks later and then delete that one too.

=== My writing process was aspiring, to say the least, because I wasn’t actively and deliberately doing the thing I said I wanted to do — which was write.

In 2013, I challenged myself to write one Answer per day on Quora for a year straight. Just one.

_*300 words. 500 words. 900 words. It didn’t matter.*_

Just one thoughtful moment, story, Answer, every day, 365 times in a row.

=== Volume, I thought, would make me a better writer.

Do you know what happened?

About two weeks in, I had my first Answer get over 10,000 views.

After a month, I had one of my Answers republished by Inc Magazine. A few weeks after that, HuffPost. A week after that, Popsugar. Then TIME. Then Forbes. Then Fortune.

After three months, one of my Answers landed on the front page of Reddit, accumulating 1 million views in two days.

After six months, I had racked up several million views on all my Quora Answers, and been republished by ten of the biggest publications on the Internet.

At the nine month mark, Quora let me know one of my Answers had been selected to be published in their 2014 print anthology — a feat I’d been told by my teachers in college could only be achieved via manilla envelope and carrier pigeon.

=== And in less than a year, I was awarded a Top Writer badge on the platform.

In the most simple way, I improved as a writer simply because of how many hours I put into practicing the act of writing. One Quora Answer per day took me anywhere from 30–60 minutes.

The more I wrote, the more comfortable I got with the page.

The more comfortable I became, the faster the words would flow.

Some days, I would write two Answers. Three. Even four.

The more I shared, the more feedback I received — directly through comments, and indirectly through data of views and shares and Upvotes.

And the more feedback I received, the more I slowly but surely began to understand (consciously and subconsciously) what worked, what didn’t, and where my most natural voice sat as a writer.

=== Volume stretched me outside my comfort zone, and kept me flexible.

At the same time, however, I was also working on my first book, Confessions of a Teenage Gamer.

It was a memoir about my emotionally complicated and vulnerable adolescence, and the thought of sharing a rough draft was nauseating. Like most writers, I put a tremendous amount of pressure on myself to make this story, my first real story, a masterpiece.

I wanted it to be perfect — and as a result, spent hundreds (if not thousands) of hours refining single pages at a time.

=== I began working on Confessions in December, 2012, and carried through until September, 2016.

It was a process I kept hidden, aside from the occasional Salon-style reading I would attend with one of my former teachers from Columbia College Chicago, or the sporadic email with an attached chapter to a friend, quickly followed by a second email that said, “Never mind, don’t waste your time. It’s awful.”

When I started writing on Quora, however, it was impossible to keep the memoir material separate.

I was toiling day and night with nostalgic moments from my childhood, reflecting on my years playing World of Warcraft as a teenager, searching for lessons learned in the muck of my depressive adolescence. When it came time to write my Quora Answer for the day, I couldn’t help but gravitate to the ones that asked, “Should we ban World of Warcraft since so many teenagers were addicted to it and had their lives ruined?”

Since I was already flexible, my fingers began to move as fast as my thoughts came barreling.

My Quora Answer to the above Question went semi-viral, accumulating close to 100,000 views. This was also the Answer that Quora included in their 2014 print anthology — an Answer I’d written in 20-some minutes one afternoon, at a coffee shop after a long day of work. It was a compressed version of many of the themes and longer stories I’d been working through for Confessions, and was the first time some of those concepts were validated out in the world. Reading through people’s comments, I started to get a better sense of what resonated and pulled at the heart strings.

=== Over time, these two modes of practice began to play heavily off one another.

My daily writing on Quora kept my fingers and imagination flexible.

My nightly writing sessions allowed me the time and space to think through concepts on a much deeper level.

Some of my most popular Quora Answers — short stories and lessons learned that flew onto the page in a matter of minutes — were the result of dozens of hours spent writing and deleting, writing and deleting much longer material late at night. And conversely, much of the progress I made on Confessions came from insights I’d gained through the hundreds of Quora Answers I’d published (and received feedback on) out in the open.

=== I am a firm believer that both modes of writing, volume and refinement, are required for long-term success.

For two reasons:

*First*, should you ever pursue a career as a professional writer — whether that’s copywriting, ghostwriting, content writing, or any other kind of writing — the most valuable skill you can have in your arsenal is the ability to write well, fast. Nothing teaches this better than volume, and daily writing on the Internet.

*Second*, it’s worth admitting that 30–60 minute sessions in which you write, lightly edit, and then share, should never be considered “final drafts.” They are rough drafts — and that’s their purpose. They are sketches. Somewhere you can fly through a bunch of ideas, quickly, and then send them off. You’re throwing paint at the wall. It’s liberating. It’s a means for discovery. But consider this the stretching that comes before the heavy lifting.

=== A writer, a true writer, is made through a combination of both.

Some of this happens inherently through volume.

_*Writing an hour per day will naturally improve your style, structure, and voice.*_

=== *But if you really want to improve, you have to edit.*

You have to re-write, from scratch. You have to throw away, start again, throw away, start again. You have to write the same story from fifteen different perspectives. You have to read it aloud. And then, once you’ve spotted a tangent or unnecessary explanation, you have to be alright with reaching for your knife to amputate — even if it means cutting your favorite paragraph, a hilarious metaphor, a beautiful sentence, or sometimes even a beloved character.

*If it doesn’t add significant value to the Question that’s being asked, it’s gone.*

=== Over the four years I spent working on Confessions, I wrote and re-wrote the entire book three times over.

My first draft was close to 1,000 pages, single spaced. My second draft, which didn’t include a single paragraph from the first draft, was close to 800 pages. My third and final draft, which was structured in a completely different way than the first two drafts, was 300 pages. I chopped more then just scenes and descriptions. I removed entire chapters and wiped away characters and plot lines, reducing the story down to its most common denominator.

=== Most writers don’t have the patience to do this.
The ones that do, publish once every few years.

Some, once a decade.

They take their fragile manuscript, load them into a manilla envelope and then fasten their package to the foot of a carrier pigeon addressed to their ideal publishing house. Some envelopes find their way into the hands of an eager editor — who returns an owl awarding them with a small advance and a book deal. Most lie dead with all the other forgotten manuscripts in a pile beside said editor’s desk, while the writer returns to his study to begin his or her next multi-year excavation.

=== Arguable worst, other writers fall victim to the Internet.

They race through rough draft after rough draft, chasing instant gratification and the next Like, Comment, and Share, never once bothering to put their story or article away, sleep, and reassess with fresh eyes in the morning. As a result, they become blogger more so than writers, and measure their success horizontally (opposed to vertically), chasing page views and exposure more than depth and understanding.

=== In order to become a successful writer in the digital age, you have to do both.

You have to get in the habit of sketching, of sharing on a daily basis. And you have to make time to sit quietly in silence and explore, for hours and hours, _*your inner Mariana’s Trench.*_

*Without volume, your depth will go unnoticed.*

*And without depth, your volume will be timely — but not timeless.*




