


=== Title: "Scientists Discover Biophotons In The Brain That Could Hint Our Consciousness is Directly Linked to Light!"

=== Source Link: http://educateinspirechange.org/science-technology/scientists-discover-biophotons-brain-hint-consciousness-directly-linked-light/

"Scientists found that neurons in mammalian brains were capable of producing photons of light, or “Biophotons”!

The photons, strangely enough, appear within the visible spectrum. They range from near-infrared through violet, or between 200 and 1,300 nanometers.

Scientists have an exciting suspicion that our brain’s neurons might be able to communicate through light. They suspect that our brain might have optical communication channels, but they have no idea what could be communicated.

Even more exciting, they claim that if there is an optical communication happening, the Biophotons our brains produce might be affected by quantum entanglement, meaning there can be a strong link between these photons, our consciousness and possibly what many cultures and religions refer to as Spirit.

In a couple of experiments scientist discovered that rat brains can pass just one biophoton per neuron a minute, but human brains could convey more than a billion biophotons per second.

This raises the question, could it be possible that the more light one can produce and communicate between neurons, the more conscious they are?

If there is any correlation between biophotons, light, and consciousness it can have strong implications that there is more to light than we are aware of.

Just think for a moment. Many texts and religions dating way back, since the dawn of human civilization have reported of saints, ascended beings and enlightened individuals having shining circles around their heads.

From Ancient Greece and Ancient Rome, to teachings of Hinduism, Buddhism, Islam and Christianity, among many other religions, sacred individuals were depicted with a shining circle in the form of a circular glow around their heads.

If they were as enlightened as they are described maybe this shining circle was just a result of the higher consciousness they operated with, hence a higher frequency and production of biophotons.

Maybe these individuals produced higher level of biophotons with stronger instensity because of their enlightenment, if there is any correlation between biophotons and consciousness.

Even the word enLIGHTenment suggests that this higher consciousness has something to do with light.

But one of the most exciting implications the discovery that our brains can produce light gives, is that maybe our consciousness and spirit are not contained within our bodies. This implication is completely overlooked by scientists.

Quantum entanglement says that 2 entangled photons react if one of the photons is affected no matter where the other photon is in The Universe without any delay.

Maybe there is a world that exists within light, and no matter where you are in The Universe photons can act as portals that enable communication between these 2 worlds. Maybe our spirit and consciousness communicate with our bodies through these biophotons. And the more light we produce the more we awaken and embody the wholeness of our consciousness.

This can explain the phenomenon of why the state of a photon is affected simply by consciously observing it, as it is proven in many quantum experiments.

Maybe our observation communicates something through our biophotons with the photon that is being observed, in a similar fashion as quantum entanglement, like light is just one unified substance that is scattered throughout our Universe and affected through each light particle.

Of course, nothing of this is even close to being a theory. But asking questions and shooting such metaphysical hypothesis might lead us closer to the truth and understanding of what consciousness is, where it comes from, and what are the mysteries that hide within light.

References:
– http://bigthink.com/robby-berman/there-are-biophotons-in-the-brain-is-something-light-based-going-on;
– https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4267444/;
– https://arxiv.org/abs/1708.08887;
– https://www.livescience.com/28550-how-quantum-entanglement-works-infographic.html;

Source: Life Coach Code

https://www.lifecoachcode.com/2017/09/21/scientists-discover-biophotons-in-the-brain-hint-consciousness-light/


