

=== Title: "Crystal Technology and Alien 'Humans'"

=== By: Peter R. Farley


=== Source Link: http://educate-yourself.org/cn/crystaltechnologyandnwo24nov04.shtml



[Editor's Note: Peter Farley obtains some truly fascinating information. There are many important pieces of the hidden alien agenda contained in this book except that corroborates information I've received from other sources, including former Illuminati programmer Cisco Wheeler. If you've been reading the Adventures of Don & Carol Croft along with the Croft Daily Reports, you know that reptilian aliens are now occupying human bodies at an exponential rate of growth. This, of course, is part of the alien agenda to take over and control this planet and use whatever remains of the human population (after the Great Dying from contrived wars, famine, chemtrail poisoning, vaccine-originated stealth diseases, domestic concentration camps, etc.) as mind controlled slaves and human robots. Stephanie Relfe had forwarded a couple of revealing articles that discuss the presence of reptilian bases beneath hospitals and a tie in with satanic blood drinking. When I touched on this area during a recent phone conversation with Cisco Wheeler, she verified that negative reptilian 'walk-ins' are indeed taking over human bodies in hospitals in one of two ways: 1. During operations, controlled surgeons are taking patients to the edge of death and "driving the human soul out of the body using a specific satanic ritual and then a reptilian steps in". She said that when the patient returns home, the family members notice a big change in personality and the person now seems to be so 'different'. That's a big tip off that a walk-in took place. That patient may or may not have been scheduled for an operation. Once you're admitted to a hospital, you can be manipulated with drugs, hypnosis, and advanced mind control technologies (almost every hospital today has mind control equipment and the personnel to use it) without your knowledge. Al Bielek mentioned as far back as his 1992 video on Mind Control that selected individuals are being programmed in hospitals without any conscious knowledge of what had been done to them. 2. New born infants, who may be human (with souls or without souls) or alien/human hybrids are being infused with reptilian souls using similar satanic rituals that drive out the resident human soul and replace it with a reptilian presence. Cisco also mentioned that the 13 Illuminati bloodline families carefully maintain a 60/40% ratio of reptilians to humans within their ranks. If they became all reptilian, she said, the race would die off as they need the human energy template and genetics to expand their ranks and utilize humans for high level satanic rituals where Mothers of Darkness (always programmed human females) pull down demonic beings from the astral plane into the encircled pentagram for interrogation and manipulation. Elaborating, Cisco said the Rockefellers, for example, are full reptilians, while the Collins family are human. Hillary Clinton is a full reptilian and very high up in the Illuminati, while Bill Clinton is only half reptilian, but he apparently can still shape shift into reptilian form. Whether of human or reptilian genetic stock, all Illuminati family members are ritually abused, mind controlled, and dedicated to serving the satanic agenda. ..Ken]. 

By Peter R. Farley <<peter6264@hotmail.com>>
http://educate-yourself.org/cn/crystaltechnologyandnwo24nov04.shtml
November 24, 2004 

From my new book, The True Nature of Planet Earth: 

"Crystal technology lies at the heart of mankind's communications technology, from radio transmitters to television sets to computer chips and more. They also lie at the very heart [as explained in earlier volumes] of temple technology and how it is used to power the New World Order's control over Man. They were also the power behind the seeming miracles performed by Atlantean technology and are already beginning to once again be the power at the very center of the 'new' Atlantis as well. To help comprehend some of the properties of quartz crystal we turn to Alice Bryant & Phyllis Galde in their book, The Message Of The Crystal Skull: From Atlantis to the New Age. Their description of how crystals can be grown provides us with a metaphor for so many areas of life and how life is often being created or constructed in sundry other areas of the Universe. Crystals can be grown from what is known as the crystal seed. As Bryant and Galde explain, any piece of natural quartz crystal can be a seed. 

Quartz crystal will dissolve in water under intense heat and pressure, the liquid crystal cells appearing then to have a "memory" that makes them seek out any nearby existing crystal to attach themselves to, thus building a new, perfect, latticework crystal structure. Even as a tomato seed needs nutrients such as water and sunshine and warmth to grow, so too will a crystal seed not grow without a nutrient. In this case, the nutrient is silicon dioxide. The combination of pressure from an earthquake and the heat produced from a volcanic rupture of the Earth's crust will cause the seed to grow. It will then grow rapidly, like a spiral staircase, growing either right- or left-handed, clockwise or counterclockwise [male or female]. This is not visible to the naked eye though, for a crystal has smooth sides. When a crystal is submerged in a tank containing a liquid of the same light-refraction index as the crystal, and a polarized light is then passed through it and observed through a polarized screen, the crystal will show a sequence of colors ranging from red to yellow to blue, similar to a rainbow. This equates with Light breaking down into its various colors, just as the Light of the FATHER breaks down into various frequencies to create the dimensional levels in Creation. As the analyzer is turned clockwise by an observer, the rings of energy emitted from the crystal expand in a right-hand crystal and contract in a left-hand crystal. 

The energies of Creation radiate out from the Central Universe and/or the center of any smaller aspect of Creation, and then are drawn back into it creating a vortex of spiraling energies we call Spir-it. The original 'holy grail' Crystal Skull described in earlier volumes is a left-hand or female crystal which draws surrounding energies into the portal at its center. Because high quality crystal is in short supply, crystal is grown today in laboratories. The high-tech electric company, Hewlett-Packard, and many other similar companies, are growing their own crystals this way. Using a tiny 'seed', a crystal as large as a building brick can be grown in 20 to 45 days using the following technique: A large steel casing, very heavy and thick, with a top that will unscrew, is partially filled with silicon dioxide in the form of pieces of pure quartz crystal. These tiny scrap chunks of natural quartz crystal contain all the necessary elements for growing a much larger crystal. The rest of the space is filled with mineralized water and the seed crystal is suspended with a tiny wire above the scrap crystal feedstock. With the top of the container tightly closed, the steel casing is lowered into a vault. 

This vault, usually subterranean, has a hatch similar to a submarine hatch that closes and then seals. The container is electrically heated to an intense temperature, resulting in tremendous pressures inside the sealed chamber. The crystal scraps dissolve and the liquid crystal cells then migrate, attaching themselves uniformly and in perfect building patterns to the mother seed crystal or matrix. After the optimum time has elapsed (a matter of weeks), the heat is turned off and the entire area is left to cool slowly. Although there are some carefully guarded trade secrets, this is the general method used. Thousands of pounds of lab-grown crystal are used every year in the electronic trade. Not only can clear electronic crystals be produced by this process but also, by carefully controlled additives to the water, select quality amethyst, citrine, blue, green, and smoke crystals can also be obtained. Large producers of crystals at this time are such countries as the United States, Germany, France, Japan, and Russia. 

As Lindsey and I 'looked' at how life forms were created in the Orion star-system in order to explain their spiritual lessons, this is how Lindsey describes what she could see: "I saw in my mind a vat of some kind of cellular soup. Then I saw a cluster of sample or seed cells being used to grow the rest of a Being. It came to me in the sense that it is a parallel to the way crystals are scientifically made from a seed crystal in a controlled environment." It also came to us both that this is exactly the way mankind was first created as a slave race of 2-stranded DNA Beings, only in this case, the electro-magnetic strands which make up the other 10 dimensional strands of our Being were stripped AWAY from us using a very similar electromagnetic technique. The crystals are grown just like the Orion 'robots' (as we like to call them) that we have seen populating many areas of life around the world. Both the crystals and the Orion robots may be compared to a hothouse tomato which is grown under controlled conditions so that the end result is superior in size, color and taste. Most often they are flawless in appearance and stature. 

And, like hothouse hybrids here on Earth, they are more 'perfect' in every way. Also like a tomato, they are better in every sense of the word because all of their needs have been met at the right time and the handicaps to their growth have been minimized. If one wanted to create a slave race, or a series of human-like robots, this would be exactly the way to go about it-and they have. Grown crystal or grown hybrids, since the needs are supplied in a controlled environment, grow very rapidly and their structure and quality are excellent compared with those left to grow naturally. Their one flaw, however, is that they do not have the same 'life force' and superior resistance to dis-ease and stress as do those that are allowed to grow naturally. It is the same, too, with wine-producing grapes-the more you stress the vine, the less juice you get but the higher quality overall. Same thing with people-if they don't go under first.
It probably wouldn't be surprising for you to find out then that most of these kind of Orion 'robots' we see existing here on Earth are the 'supermodels', the flawless beauties, the movie-stars, the yuppies of the world seeking outward power and success instead of internal satisfaction and cooperation. 

These are the idols and role models held up to us all by the New World Order-controlled media as something we should all be just like-machines existing in a robot-like world. They are the ones that most of us have admired so much and aspire to be just like, often throughout most of our lives-never coming close to that kind of robot-like perfection, though some kids these days are so programmed they do come very close. In the articles he has written for his website on the subject of 'the true nature of planet Earth', Peter tried to describe the vast number of 'energy or life forms' besides these Orion-robots that both of us have encountered along the road during our healing travels. 

Here is an excerpt from one article that gets across the initial idea of energy forms to the uninformed reader: "If you remember the work I have been doing over the past year with alien energy forms and all the different types of Being 'in human form', it is amazing to find that I have had very, very few people with whom I worked who did not take it immediately to heart once I told them what type of Being they were. All of a sudden it just made automatic sense of their lives, the things they like to do, their body type, the things they like to collect, their diets, the things they did or liked as children. Everything about their lives suddenly fell into place. "We as humans, those of us who are, think of our form as being "normal" -and that the animals we see around us are just that-'animals'-rather than being the lowered energetic forms of more advanced civilizations who helped create civilization here on Earth. 

It is the movies such as Star Wars and Star Trek that portray the normalcy of the way things really are. "Many of the aliens that we work with call humans 'squishy water' because that's all we are really made of-water and sea salt. Some of the different alien energy forms we have encountered are biological/metal hybrids, some exist more like energetic balls on their home planets, while others are exactly like the ewoks or wookies from the aforementioned movies. St. Germaine himself says there are more than 200 different kinds of Being here on planet Earth. "In our travels we have also dealt with fish people who drink three gallons of water a day and breathe through the water they drink because they have energetic gills under their chins, etc. We have worked with dinosaur-like aliens, various forms and sizes of reptilians, both those who were here on positive helpful missions as well as those who were here programmed for not such nice things at all. 

We have worked with androids, artificial intelligences, androgynous types of Beings, squirrel-like aliens, many, many turtle people of various forms, lizard and salamander people and countless others that we shall try to describe below. It is the true nature of this planet that it is as Peter has always said, just like a 'Star-Wars bar'. "Seventy-two percent of this planet is in fact 'not human'. It is that way and has always been kind of that way, Beings here from so many varied places to either help or hinder the planetary ascension and/or the New World Order's plans for total planetary control. "This then means that only about 28 percent of humans are just that, truly human. "Since so many aliens from so many higher dimensional levels need to come here for whatever purpose, they must either choose to be born through the womb, or they must simply 'walk-in' to another human form. What happens, however, is that they still bring their 'alien' dimensional energy forms with them in doing so. 

As The Destiny of Souls describes it "they project a human body here on planet Earth." If they come through the womb then they create their own earth-world persona. If they walk in, then the sense of who that person is seems to change like they are no longer who they once were. In my experience, the basic ego-driven core shell of the person remains the same when this happens yet it does not understand why it suddenly no longer likes the same things. Often dietary needs will change overnight as well. "Each of these Beings comes in, however, with a sense of purpose, a sense of mission, something they are drawn to and seem to know they should be working with or on-a certain field of enterprise or expertise. "Many of them are also implanted with homing chips, transmitters and sometimes even 'minute television cameras' located behind the eyes so that their home planetary peoples can either see or monitor what is taking place around them here on planet Earth.

I know there are some from far-distant places in the Universe not interacting with what is taking place here but simply watching the course of Creation's fight for freedom. Some have also either been through what we are going through in warding off the darkness, or know at some time it may be their very same lot. "There are also angelic Beings in human form, ranging from novices (who are, incidentally, torn apart by the cruelty and violence here on planet Earth), through intermediate levels, right up to arch-angels and dark angels who are here to heal and help others heal, and to watch over their flock of lesser angels. "All these Beings usually have some sense of being different, of not belonging. These are the most common words we hear -"I feel like I don't belong." Their energetic forms or morphogenetic fields which encase the physical form are their true forms and their true natures. Thus a wookie who in physical form is 5' 9" may have an energy form of somewhere near 8' tall, being as he is, the bigfoot stereotype. Ewoks seem to inhabit smaller, more-rounded shapes, etc. Genetics are not effected by energy forms, except for anomalies such as the racially specific diseases and traits. "These energy forms often dictate or complicate the health problems of the human forms. Certain allergies to foods, pollens, areas, etc.

The fish person would die without the three gallons of water a day that she breathes through, yet this is the first thing 'normal' doctors try to get her to do. The turtle people range from those who like the east coast humid environment to the more desert turtle kind (Interestingly, those I have dealt with of this type often live out of motor homes and trailer parks, etc. where the image is of carrying your home/shell upon your back). Almost always the physical form is fighting to fill out the energy form which surrounds it. Thus people's weight, etc., is not necessarily a product of anything physical, and often little can be done about it except disconnecting them from that alien form and making them fully human. Some of the smaller physical forms suffer when they are trying to 'fill out' a larger morphogenetic field, the bones will continue to grow while the skin will not stretch to that level as in one case I have seen. Shoulders round, hips spread-many, many different factors dictate the way the human form develops and tries to accommodate the often large differences between its energy form and the human one involved. 

This is evident to anyone of us if we but sit back and watch the people coming in to any Starbucks almost anywhere in the world. "Add to this the astrological factors, environmental factors, societal factors, genetic factors, and you will see why modern medicine is useless in trying to deal with people who they see as all being human. "Another thing we have found is that these 'alien Beings' are often specialists in some field, here to do work for and with the planet. Many are here to work with the animal life (the lowered version of their own 'animal' species in the higher dimensional worlds of the Universe). Some have specific gifts in terms of nature and the plant life of the planet that originated back on their own planets but were brought here during the early formation of the planet. Sometimes, however, they are programmed specialists waiting to be triggered to perform deeds that will make Earth society more fearful or paranoid. Often they are 'Manchurian candidates' programmed for some future act as things reach a head during this war between Mankind and the New World Order.

Peter R. Farley
Roswell, NM 88202

http://www.cosmologies.com/treeoflife/
http://groups.yahoo.com/group/4truthseekers






