== dream_meanings.adoc

> *Alligator* (crocodile): Ugly mouths, cruel teeth, and dangerous tails.  Examine vicious speech (teeth), and dangerous (behaviors) tails.  Your behavior may have been destructive.

> *Dog*: Can alert for danger.  Be on guard or you will get into trouble.  You see the dog when believing yourself safe or possible attack to come.  Dog is friendly yet has ferocity.  In dreams he represents friendliness and unfriendliness.  Look first for unfriendliness in humans. Dream of a hostile dog can be a warning of hostile attitudes but the right attitude the experience of a dog can sometimes be harmonizing.

> *Bird*: Relate to beauty, joy, and love.  Lifts from lower-self to higher-self.  Birds lift man above the material and selfish world (earthiness), to a higher spiritual world (sky or heaven).  The birds activity in the dream hints at it's meaning.  Bird also symbolizes the thymus which is also related to love.  Birds represent true wise love without demanding anything in return.

> * Humans and Animals have three main drives: self-preservation, perpetuation of species, and sustenance; man must spiritualize them.  Wrong drivers are: gluttony, exploitation of others, and adultery.  This corrodes the physical and spiritual.

> *Cat*: Independent animals.  In humans it can be *constructive*, but if carried to extremes it makes for *uncooperative* and *isolation*.  A cat also howls, spits, and rips furniture.  The term for gossip is "cattiness". Petting a cat in a dream represents pleasure in a negative emotion.  Concern of health of the cat is concern of destructive habits.  The fatter the cat the bigger the problem. Death of animal can mean spiritual progress or also goodness, protection, protective concern if your life was saved from an animal.

> *Squirrel*: According to Cayce animals relate to negative, underdeveloped, improper attitudes or activities in man.  If an animal is embedded in skin it is related to chronic or temporary irritation.  Part of a body part in a dream symbolizes problem with that area.

> *Insects* ad *Marine Life*: (bee or hornet): stings represent unpleasant experiences of life.  Pool stands for pool of life.  Fish show spiritual achievements. Slimy elements and hornets represent unpleasant elements of life. - All which may be overcome.

> *Bugs* and *Beetles*: Bugs = Bugging. Weak legs represent poor spiritual foundation. Unless she obeyed Spiritual Law her life would be cut short.

> *Caterpillar* or *Worm*: Represent *destruction* or disintegration.  Caterpillars eat leaves of trees or relate to *attitude* or *activity* that is destructive.

> *Ant*: means you need to apply Spiritual Truth to daily life.  Ants are associated with work and sand represents an unbalanced foundation.  Do not allow the worry of business to overshadow spiritual development or ideals.  Keep each in its own sphere.  Spiritual knowledge comes through application as well (be love + show love). "Thow art the God within thine own self" - Cayce Through choices make or break thy own spirit to accomplish what is set before thee. 

* "If spiritual purpose is set then I am with thee."

* "Keep heart in attunement and every condition will open at the right time, place, and manner."

* "The higher the dreamer climbs spiritually, the less conscious of physical pull."

* "Admonished not to look back now - that he has begun his march forward"

* "Keep thine self right and all will come out well."

--- Passages from Dreams Your Magic Mirror







