

=== Title: "Ending Suffering In Yourself"

=== By: Penney Peirce 

=== Transcribed:  April 11, 2018 - A snippet from the book "frequency"

_"You can turn the unhealthy habits into conscious sensitivity by catching yourself in a reaction, being with the experience, and choosing an alternative healthy feeling habit to experiment with instead."_


=== Inspired Writing Snippet

"Suffering, even great physical pain and emotional loss, dissolves when you stop looking at it and for it.  It disappears when you stop agreeing with it or fighting it.  It becomes nothing when you cease to extract identity from it.  In the higher realms, there is no suffering, there are no victims, no saviors, no leaders, no followers, no haves and have-nots, no here and not-here.  In higher frequencies, you know *the power of being*.  *Being reveals presence, and presence reveals love as the basic unchanging nature of self and life.*  In any moment, You can Be.  You can look for and feel presence; you can expect the surprise return to the love you've never left.  There is no pain in love, only in separation from love, and feeling separate is the choice to suffer.


In the higher realms, your self is our self is the Self, and the self is one shared experience of loving presence.  If you think you are not the one Self, or that another is not the one Self, that it is possible to be lost, then you suffer. Thinking of "them," or a space between, or a vacuum, makes an artificial gap, because *there is nothing outside you*, no strangers, nothing foreign, nowhere that presence can escape to make an emptiness.  As soon as you pretend to have a gap in the continuum of presence, you create suffering, which is doubt and fear which is separation, which is insanity.  It is only in the mind.  The moment you re familiarize the world, melting it back together again within yourself, the gap dissolves and indivisible presence reappears.  One way you see yourself as a small, finite trembling self, the other way as an unlimited, ever-expanding radiant self.

Sometimes you will feel pain, which is the resistance to natural contraction.  You need not suffer, though.  Release and move on with the wave.  Sometimes people who suffer will occur "within the space of you." in your world.  This means you still contemplate the possibility of sufferings reality.  Be with them fully, for one pure moment.  Don't' believe them, don't negate them, don't copy them- just allow their experience.  Feel the presence in them, let them feel your presence, offer it as the presence of the one Self, and let them merge into your offering as much as they wish.  As presence becomes conscious, calm certainty emerges, and they remember their true self.  They find their way out of suffering, and this frees you, too.  As the memory of love occurs, there is instantaneous healing, sudden positive change, and personal transformation- in them and you.  Every dissolution of the illusion of no-love erases suffering for all of us.  Every collapse of the gaps the mind makes, and suffering dissolves, like a cloud into he sky's deep blue." 





                                                                - http://penneypeirce.com/





