
=== Heart Trouble

"The heart is the center of Divine Love and perfect circulation. Its action is harmonious, vital, adequate and complete. There is no false action and no wrong action. The pulsations of life are steady, unceasing and perfect. "Let not your heart be troubled." Love is at the center of man’s being, and the calm, continuous, pulsations of life are governed by Love.

Solomon is accredited with many words of wisdom, none of which are more appropriate just here than his admonition: "Keep thy heart with all diligence, for out of it are the issues of life." (Prov. 4:32) In the days when we had no knowledge of whether the emotions should be expressed, repressed or suppressed, the reference to the heart was hardly as significant as it is today. Now, in the light of experience, there is no question but that anything that touches the sympathetic nature of man has within it the power to build up or destroy the physical body of man. The daily record of fatalities from "heart trouble," bears evidence of this. Sudden shock, terrific loss - particularly loss of love - FEAR, all kinds of fear, are some of the thoughts which quickly manifest in the body of man as "heart trouble." The remedy for this is LOVE. "Perfect love casteth out fear," and a Divine fearlessness, a singleness of purpose, a determination to think only God-like thoughts, should be used in treating heart trouble.

Almost every case of heart trouble can be traced to thoughts of strain and in harmony; sometimes to disappointment or disagreement with a loved one; or to a feeling of loss from financial reverse. A belief that we can be in a position from which God absents Himself. We reiterate, a remedy for all heart trouble is LOVE. The heart is known as the center of love, which is the healing balm for every inharmonious thought. As we recognize our Oneness with Infinite Intelligence, we are set free from uncertainty and pain. As long as we realize that our heart is a living center, through which the Love of God flows to bless eternally, not only our own lives but the lives of all whom we contact - as long as we realize this, our heart cannot be troubled.

Another thought to be handled in treating any kind of heart trouble is the thought of age. The race-suggestion carries a strong belief about the unpleasant conditions which may present themselves as one "grows old." Among these, is the physical condition termed hardening of the arteries, which hinders the free flow of blood to the brain. A treatment must be so formulated as to recognize that there is but One Mind, consequently, no thought of depression, fear or suggestion of imperfection can blow through It. Man is birthless, deathless, ageless Spirit; and this should be the consciousness of our work. This leaves nothing to be born, mature, decay and die. Life cannot grow old. God - in us, and through us, as us - can only express according to His Own Nature, which is Perfection. Therefore, the Law of our being is the Law of perfect assimilation, elimination and circulation; and it is the law of obliteration to anything unlike Itself. A knowledge of our Oneness with the God-Life all about and within us, that this life is governed by Divine Law and Harmony within us, that your only need is to cooperate mentally with the Law of Life, will heal when we recognize Its presence and activity within us.

Some physicians now claim that the action of the heart is a reflex action, and that the dilation and contraction of the heart is controlled by sympathetic nerve centers in the spine; and while they say that will does not control the heartbeat, emotions do affect the heart and sudden and unexpected grief often causes instant death. Loving thoughts for all will remove tenseness, stimulate the heart into healthy action, and send new life to every part of the body. "Blessed are the pure in heart for they shall see God."

--- Passage from The Science of Mind, A Philosophy, A Faith, A Way Of Life

