


=== Title: Hemingway's Writing Tip That Will Save You Time and Energy

=== By: Tanya Hall CEO, Greenleaf Book Group @tanyahall

=== Source Link: https://www.inc.com/tanya-hall/hemingways-writing-tip-that-will-save-you-time-energy.html?cid=sf01001&sr_share=twitter



*You don't need to move to Paris, but you should reread your work as you go.*

"When it comes to writing a book, there are many reasons to emulate the masters. Proust famously wrote in bed, while Joan Didion took an hour before dinner to read that day's writing with a drink in hand. Most authors have a strict schedule for writing days that they adhere to without question. But if you're not Proust or Didion, rather a first-time author, you may be overwhelmed by the process of writing a book. We can look to another literary great, Ernest Hemingway, for some useful advice for managing the writing process.

Hemingway, most famous for standing while writing, was also a proponent of starting each writing session by reading what he had previously written. In an interview with The Paris Review in 1958, he said, "When I am working on a book or a story I write every morning as soon after first light as possible...You read what you have written and, as you always stop when you know what is going to happen next, you go on from there."

Few of us have several hours a day to dedicate to writing, so it's not always practical to read your entire manuscript before diving back into work. But there is value to taking time to reread your manuscript at pivotal points in the writing process before moving forward. Most notably, after several months of writing, authors can easily lose track of which topics they've covered and which still need to be addressed, especially if they've been jumping around the manuscript while writing.

The easiest way to implement Hemingway's process is to assign reading days during the outline phase. If the book's topic is complicated, consider stopping to read the full manuscript after each chapter is completed. If the manuscript follows a more formulaic outline, try reading the manuscript each time you finish a major section. Here are a few reasons this will be helpful to you in the long run.

*Avoid Repetition*
In nonfiction books, there can be several logical places to cover a topic -- but you don't necessarily want to do so at every opportunity.

For instance, in a recent rereading of my own book, I noticed that I had written 2-3 times about the importance of an editorial calendar for authors building an audience. Clearly, I think it's good advice. But reiterating it so often actually lessened its impact. When you reread your own manuscript, keep an eye out for redundant information and consolidate it in the chapter or section that will give it the most power.

*Maintain Voice*
We all have days when we think we missed our calling as a comedy writer and others when it's painful just to string a sentence together. It's difficult to maintain a consistent voice over several writing sessions with outside factors continually affecting our moods and concentration.

Decide on a general tone for the book before you write your first words. Will the book be lighthearted and approachable? Or will it be serious and thoughtful? The answer depends on the intended audience, and it shouldn't fluctuate throughout the book. Regular rereading will help you identify and adjust your work from those off days when you missed the mark.

*Avoid Writer's Block*
Just as you'll have days when the voice is off, on some days the blinking cursor will mock you. Rather than sitting patiently and waiting for the muses to visit, consider re-reading the last chapter you wrote. Chances are that you'll remember where you wanted to go next and find some momentum. Going forward, try to leave a writing session with a clear path forward. (Hemingway was also a fan of stopping for the day before he felt depleted.)

*Save Time*
We've all heard the expression "you have to spend money to make money." The same idea applies to time in this scenario. By spending a little extra time rereading your manuscript, you're more likely to save time in the long run.

Trudging forward without looking back on what you've already written is a recipe for heavy editing later. There's no getting out of editing altogether, but hiring an editor for a line read is a much smaller investment of your time and money than hiring someone to rework sections and move around entire paragraphs or chapters.

Taking the time to reread your work may not make you the next Hemingway, but it will improve your writing and help you maintain your sanity during the writing process."

The opinions expressed here by Inc.com columnists are their own, not those of Inc.com.

Published on: Oct 26, 2017



