


=== The Law of Correspondence

"The limit of our ability to demonstrate depends up on our ability to provide a mental equivalent of our desires, for the law of correspondence works from the belief to the thing.  But it is within our power to provide a greater mental equivalent through the unfolding of consciousness; and this growth from within will finally lead to freedom.

What we demonstrate today, tomorrow and the next day, is not as important as the TENDENCY WHICH OUR THOUGHT IS TAKING.... The dominant attitude of our mind.  If every day things are a little better, a little happier, a little more harmonious, a little more health-giving and joyous; if each day we are expressing more life, we are going in the right direction.

And so we meditate daily upon the Universe of All Good, the Infinite Indwelling Spirit, which we call God, the Father, incarnate in man, trying to sense and to feel this Indwelling Good as the Active Principle of our lives.  This is what the mystics call *"The Man of the Heart"*, or *"The Angel of God's Presence."*  This is why they taught that there are always two, for there is _what we seem to be, and what we really are._  As we contact this Higher Principle of our own lives- which is Perfect and Complete, needing nothing, wanting nothing, knowing everything, being happy and satisfied- and as we daily meditate upon this Indwelling God, we shall acquire a greater mental equivalent.

For those who have always dwelt on limited thoughts a very good practice is to dwell upon the magnitude of the Universe.  Think how many stars there are, how many fish there are in the seas, and how many grains of sand on the beaches.  Think of how big the ocean is; of the immensity of space, the bigness of everything, the grandeur of everything.  Mechanically, if necessary, compel the mentality to cognize Reality.  Compel the consciousness to recognize Truth through reason, if no other conviction comes.

Think, see and feel activity. Radiate Life. Feel that there is that within which is the center and circumference of the Universe.  The Universe is the result of the Self-Contemplation of God.  Our lives are the result of our Self-Contemplations, and are peopled with the personifications of our thoughts and ideas.  Accept this without question for it is true.

Nothing is real to use unless we make it real.  Nothing can touch us unless we let it touch us.  Refuse to have the feelings hurt.  Refuse to receive anyone's condemnation.  In the independence of your own mentality, believe and feel that you are wonderful.  This is not conceit, it is the truth.  What can be more wonderful than the manifestation of the Infinite Mind?"

*"Awake thou that sleepest, and arise from the dead, and Christ shall give thee light."* 

*"Prove me now herewith, saith the Lord of Hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it."* 

*"Be firm and ye shall be made firm"* 

*"Act as though I am and I will be."* 

*"Onlook thou the Deity and the Deity will onlook thee."* 

*As thou hast believed, so be it done."* 

*"Ask and it shall be given unto you."*

*"So shall my word be that goeth forth out of my mouth- it shall prosper."*

--- Passage from The Science of Mind, A Philosophy, A Faith, A Way Of Life

