


=== Article Title: Massimo Vignelli: The 3 Traits of Great Creatives

=== by Tanner Christensen

=== 99u Website


> Famed designer Massimo Vignelli passed away this past month at the age 83. As a result of his nearly 60-year-long career, Vignelli left behind a lengthy legacy of creative wisdom. Included among the libraries of insights from his career, Vignelli gave us three essential components for building a fulfilling and successful creative life: vision, courage, and determination.

> Without vision, nothing separates you from any other “pencil pusher.” Without courage, you’re likely to fall victim to the seemingly endless stream of fear of failure, incompetence, or imperfection you’ll face during your life. And without determination, all of the vision and courage is useless as even the smallest hurdle will cut down your momentum.

> Take Vignelli’s wisdom and find your vision, train yourself to be courageous, and determine to be determined.

https://vimeo.com/14421480[Massimo Vignelli Video]

> As Vignelli explains in the video above: Nearly anyone can learn to use the tools and strategies other designers and illustrators use:

> Train yourself to have vision, courage, and determination. These three things, to me, are very important. You have to work with people who have that, and at the same time, you have to have it, so that you can install it on people. You can excite them. You can show them you have a vision. You can show to them what they cannot see. At the same time, you should not have a fear of failure—this is what marketing is all about: fear of failure. Instead, you have to have courage. Courage not to fail, or courage, even, to fail! On top of it, you need to have determination to reach your objectives. Vision, courage, and determination will bring you where you want to go, but without them, it would be a miserable life.


:p

