
=== Mental Expansion (II Cor. 3:18)

> But we all, with open face beholding as in a glass the glory of the Lord, are changed into the same image from glory to glory, even as by the Spirit of the Lord.

> As our thought is opened and we behold the image of eternity within ourselves, we are changed by this image into a newness of Life.  This is accomplished by the Spirit of God.

> The subjective state of thought is the creative medium within us, which fact psychology has proven beyond any question of doubt.  Emerson tells us that we are inlets and might become outlets to the Divine Nature.  We are already _inlets,_ but we must _consciously become outlets._ A great mystic tells us that the upper part of the soul is merged with God and the lower part with time and conditions.  Plotinus says that when the soul looks to God alone for its inspiration, its work is done better--even though its back is turned to its work.  And Jesus tells us to seek the Kingdom Of God first and that all else will be added unto us.

> Now the image of God is imprinted upon each one of us and all reflect the Divine Glory to some degree.  Indeed we are part of the Divine Glory.  When our thought is turned from limitation to the creator glory, we then reflect that glory.

> When the subjective state of our thought receives its images from Reality, it, in turn, reflects this Reality into all that we do.  Gradually, as this process takes place, the outer man becomes changed, and as his concepts become enlarged, so his conditions and physique take on a newness of life.

> And this change in the outer is brought about by the Spirit of God.  The Spirit of God--being the One and Only Presence in the Universe--brings about events and re-molds conditions after It's own likeness.

* (Page 489-490)
* The Science of Mind - A Philosophy, A Faith, A Way of Life
* Ernest Holmes
* Introduction by Jean Houston, PH.D.






