
=== Nerve Trouble

"As we come to realize that thoughts are things we shall also see that different kinds of thoughts will produce different types of effects. There is but one final Truth or Reality, but It is always presenting us with varying forms of Itself. These forms are temporarily misshapen by the creative power of our own thought. For we must not forget that what we call our thought is really the place where we re using Creative Mind Itself. Our thought is creative, not because we will it so, but BECAUSE IT ALREADY IS SO. WE CANNOT CHANGE THIS NOR ESCAPE FROM ITS EFFECTS IN OUR LIVES.

Consequently we see that certain thoughts would depress while others would exalt. And all according to the One Law governing our lives. With this in mind, then, we understand what is meant by saying that certain thoughts should be used in treating certain cases.

Let us consider what kind of thought to use in treating never troubles. We do not deny that people suffer from this or any other cause. We do, however, affirm that thought may help and has the possibility of completely healing them from the trouble. The nerves certainly represent the highest form of intelligence running through the flesh. They really represent mind in the highest form it takes as it controls the human body.

The general treatment for nerve disorders should incorporate thoughts of peace, poise, and power. There is no strain or struggle in the Universe. All the actions of Life are harmonious, steady, sure and quiet. Because the nerves are so responsive to thought, they react immediately to a statement of harmony. An understanding of the truth that good alone is real and true, gives us the faith essential to an establishment of a firm, unwavering mind, which is necessary if one is to have firm, steady, sensitive, quickly-responding nerves. Our thought must never waver from the premise of One Power, which is an impersonal, infinite Power for good.

We train our mind to contemplate the good, the enduring, the true. That which has caused depression, discouragement or indecision, must be neutralized by our refusal to allow it to register. Realize that the Spirit within you manifests as perfect harmony, and that every cell, atom and organ of your body is functioning according to the Divine Law. Say: "I am filled with peace, strength, power and decision of Spirit. The life forces flow freely, peacefully, and harmoniously through every atom of my body, I am complete and perfect now. The all-powerful Mind of the Indwelling Christ in me dissolves and dissipates from my mind all belief in indecision, anxiety, depression and discouragement, for I dwell in the real of peace."

We must heal ourselves from worry. This tension is relaxed as we gain confidence in good, in truth and in beauty. Faith must overcome fear, and strong statements of faith should be used to erase the thoughts of doubt and worry that have assailed us. "I have faith. I am faith. I abide in faith. All doubt and fear have left me. I understand why it is that I can remain in faith. I have complete confidence. I do not waver nor falter in my faith, for I know that God, the Living Spirit, is the only Presence there is or ever can be."

We should also erase the thoughts of yesterday that would rob us of today’s happiness. "There is nothing arising out of the past that can disturb me. The past, the present and the future are one unbroken stream of Good. I loose all thoughts that in the past have caused anxiety. The Spirit knows no past and is not affected by the belief in any. The past is swallowed up in the victory of a perfect present, which is filled with love and protection."

Equally we must not have fear for the future. "I see that the future is bright with promise. It beckons me forward into a more complete realization of my own worth and my rightful place in the Universe. All my tomorrows will be happy and filled with harmonious occupations. I look to the future with great and pleasurable anticipation, knowing it will expand my opportunity for radiant self-expression. I love my past and my future and understand that they are but continuations of the one unbroken chain of life. There is no future to be afraid of and no past to bring discord into the present."

Such statements will tend to erase any negative stream of causation that may have been set in motion in the past. Waste no time arguing with anyone over these truths. This is true and ti really works. We would better spend our time using the Law than arguing over It. Our position is to be proven by DEMONSTRATION ALONE. THIS IS THE FINAL TEST OF ALL THEORIES.

We should ready, study, think and meditate upon those statements which tend to calm, to give poise and confidence, and erase all thoughts of fear and tension. The subjective law can only operate upon that which is given it, so we must be very careful of our patterns of thought. We live in a sea of Perfect Life and we should take time to understand and sense this in our imagination. We should think of ourselves as being surrounded by perfect life and poised in an eternal calm. We are in a sea of untroubled waters of life, from which we may freely drink. We must do the drinking. No one else can do this for us. We should hold out the cup of acceptance until it is filled and overflowing with the manifestations of our desires. The chalice of the heart is held up that the heavenly flow may fill it with God’s abundant life.

The words of peace spoken to the nervous system will remove the tension which produces pain and inflammation of the nerves. There is neither irritation, agitation, nor inflammation in God, in Spirit, in Truth, and man is the Truth. "Peace I leave with you, my peace I give unto you. . . . Let not your heart be troubled, neither let it be afraid." "I am pure Spirit. My entire nervous system is pure Spirit. I am poised in harmony, in Truth and in complete calm. My nervous system is in the Spirit within me, governing my physical body with harmony. There is no need for pain. My body is pure Spiritual Substance and as such it is perfect and harmonious."

We are poised in a sense of peace, which comes from our complete faith in God as the light, power and inspiration of our life. There will be no twitching of muscles, no uneasiness or anxiety about any outcome, if we know - whether waking or sleeping - that every step of the way God goes with us."

--- Passage from The Science of Mind, A Philosophy, A Faith, A Way Of Life

