
== Physical Perfection
365 Science of Mind <ernest@holmes>

=== Recognize Physical Perfection as My Divine Birthright

*Wither shall I flee from thy presence? - PSALM 139:7*

"There is One Life, that Life is God, that Life is my life now. It is only when we live affirmatively that we can be happy. It is only as we seek the good that we can find it. It is only as we mentally align our consciousness with abundance that it can seek us out.

We have been told to behold the face of God forevermore in everything. Now we know that we do not really see God anymore than we see life. No one has ever seen life, but everyone has experienced it through living. No one has ever seen God, but some people have experienced God’s Presence so completely that their whole life has become a continual affirmation of peace, poise, and power. All persons have experienced this Presence to some degree. It is not entirely unknown to anyone.

Being told to behold God’s face forevermore means that we should recognize lief, poise, power, peace, joy, in and through everything and everyone. This has been called practicing the presence of God. We can all do this with the certainty of splendid results.

Today I recognize the Divine Presence in everything. In the midst of darkness I see Light. At midnight I sing a song to the dawn, knowing that Eternal light dissipates all darkness. Today I recognize beauty in the midst of ugliness, peace in the midst of confusion. Today I convert all doubt into certainty, all sorrow into joy, all fear into faith."

