
= thespaceship readme

== thespaceship tabulations

=== 181snippetalbaweinman.adoc
The Evolution of Humanity Explained From Deep Hypnosis!

=== aliens_confirm_disclosure.adoc
aliens validate aspects of the disclosure story

=== AngelMetatronViaChristmas.adoc
Metatron Transforms You With Light

=== TheAlienTarotReading.adoc
An Alien Forshadows Your Future With Tarot

=== aMeterorite.adoc
How Big Would A Meteorite Have To Be To Wipe Out All Human Life?

=== anotherUniverse.adoc 
A Quantum Theory Proves Consciousness Moves To Another Universe After Death

=== astralprojectionandhypnosis.adoc
We are discovering more and more about the human mind.

=== becomeASuccessfulWriter.adoc
Two keys to the process of writing explained

=== biophotons.adoc
the brain may communicate through light or biophotons

=== crystaltechnology_and_alienhumans.adoc
(alternative article on crystals - informatino not-verified)

=== dream_meanings.adoc
animal meanings in your dreams

=== end_suffering_in_yourself.adoc
let go of negative perspectives

=== generaterealwealth.pdf
setting the intention is a powerful thing

=== healingandwholeness.adoc
chapter 5: cim - love and joy quotes and concepts

=== hearttrouble.adoc
Love powers the heart and body : Science of Mind

=== hemingway_tips.adoc
what would hemingway do?

=== humanity_sacrificed_truth.adoc
by pamela aarlynn 

=== impossibleintelligenceexplosion.adoc
artificial intelligence won't take over

=== lawofcorrespondence.adoc
Put Attitude of Minds Thoughts only on Goodness : Science of Mind

=== MassimoVignelli3Traits.adoc
Designer Massimo Vignelli talk about vision, courage, and determination.

=== musclefromscratch.pdf
scientist learn to create muscle 

=== MentalExpansion.adoc
(II Cor. 3:18) Science of Mind Clipping - Shedding brings Renewal

=== negativityfast.pdf
mental exercise to release negativity.

=== nervetrouble.adoc
train your mind towards peace, strength, and power : Science of Mind

=== newbeliefgenerator.pdf
mental exercise to generate new perspective and beliefs

=== orbiesspiritualrant.adoc
a rant about two different spiritual view points

=== orbiesspiritualrant.adoc
an online chatter rant about different spiritual view points

=== physicalperfection.adoc
mentally Align and Seek The Good :365 SOM Meditational Quote

=== powerofsuggestion.pdf
mental exercise to reenergise and focus

=== releaseeverytension.adoc
release Fear & Align With Goodness and Right Action:365 SOM Meditational Quote

=== realizeaperfectbeing.adoc
No matter what the appearance is, reality is perfect; everything comes from God.

=== spacenavigationwithpulsars.pdf
using space as a road map

=== spiritual_hinduism.adoc
basic hinduism ideas and concepts

=== spiritpermeates.adoc
The Power of One Spirit and Goodness Flows Through You :365 SOM Meditational Quote

=== saywhat.adoc
Displaying some passages of Buddha

=== seeonlythegood.adoc
Release and let go of fear and low energy... Focus on the Good!

=== the_innocent_perception.adoc
A few more snipets from Chapter 3 ACIM.

=== theInnocentPerceptionCh3.adoc
Principle of Course In Miracles from Outside This Universe
"God does not believe in retributioin."

=== a_whisper_in_your_dream.adoc
Understanding Jesus True Teachings

=== WordsMatter.adoc
Eight sentences stating why words matter. - Quoted from twitter somewhere.

*Discussion* + *Decision* + *Destination*



















