


=== *Today I Recognize That I am a Perfect Being* 
===      *Living Under Perfect Conditions*

_All things were made by him; and without him was not any thing made that was made._ - JOHN 1:3

_There is naught whatsoever higher than I. . . . All this is threaded on Me, as rows of pearls on a string._ - The Bhagavad Gita


All things are threaded on the Divine, "like rows of pearls on a string."  Spiritual intuition tells us that beauty is at the root of everything.  Ugliness is its suppositional opposite.  We must sense not the opposite but the Reality.  It is this Divine Presence that we are to recognize.  For every apparent opposite we are to supply a realization of the truth about that opposite.  In this way we supply a spiritual sense that is transcendent of the form that the material sense has created.  In this way we can look at, in, and through a difficulty or a difficult situation, until we perceive the truth at the very center of its being.  Thus the devil, that is, evil or false appearance, is transmuted into an angel of light, for there is naught beside God.  If everything enduring and true comes from God, the Creator, then we may be certain that no matter what the appearance is, the reality is always perfect.  This is why Jesus tells us to judge not according to appearances, but to judge righteously. We shall always judge righteously when our knowledge is based upon the certainty of the Divine Presence, perfect at the center of everything.

Today I recognize that I am a perfect being, living under perfect conditions, knowing that the good alone is real.  I will also know that good alone is the only thing that has any power either to act or to react.  Everything that I do, say, or think today will be done, said, or thought from the spiritual viewpoint of God in everything.


