
== Release Every Tension
365 Science of Mind <ernest@holmes>
=== I Release Every Tension of Mind and Body

*Release and ye shall be released — Luke 6:37*

"Today I release all thoughts of fear from my mind. Today I lay down the burden of caring the load of responsibility of life for myself or for others. Today I relax all sense of strain. I remember that Emerson said, "The universe remains at heart unhurt"; that Jesus said, "Let not your heart be troubled." I know that I live under the government of good and am guided by Spirit. Therefore, I lay all trouble aside, seeking to look through it, beyond it, above ti; to detach it from the realm of Reality, to separate it from any consciousness that belongs to me or to anyone else, regardless of what any problem of the moment seems to be.

I align myself with the powers of goodness and of right action. I abide in perfect and complete faith in God as my ever-present good. I take up no arms to fight the negative. I turn from all fear; turn joyfully and resolutely to faith, realizing that light is immune to darkness, that the night has no power over the day, that dawn dissipates the shadows of midnight. I turn my attention to the Light Eternal, without struggle, realizing that that Light, shining through the dark places of my consciousness, will dissipate them and that I will walk in that Light in which there is no darkness. Not only will I walk in this Light, I will radiate it. I will impart it to others. I will remember the saying, "Let your light so shine before men that they, seeing your good works, shall glorify your Father which art in heaven." I will remember that the Father which art in heaven is in that heaven that is within me." — Sept 26 | 365 Science of Mind

