


=== Synopsis: How to Say?

The book titled, "What Would Buddha Say?" by *Barbara Ann Kipfer* is a collection passages that unwind the mind. Here are a few pieces of the hypnotic sentences..


> Develop patience not for pleasure but to cultivate transcendent detachment.  Let nothing that comes your way throw you.

> Be soft-spoken

> If a relationship has become difficult, it may be because you have nourished your judgment and anger, not your *compassion*.

> Listening is an art. Listen with a still and concentrated mind.  Then it is possible to be responsive to what is being.

> The blow of a whip raises a welt, but a blow of the tongue crushes bones.

> Look for many ways people communicate their love without saying it.

>  When you avoid people who differ from you, you shut yourself off from different perspectives and reduce your capacity for *creative solutions.*

> Your inner stories are based on your openness.

>  By listening deeply and openly to your inner dialogue, you can replace the inner authority figure with more loving nurturing voice.

> The more you practice concentrating on the breath, the longer you will be able to sustain a mindful listener's composure free from internal distraction.

>  Anger is like picking up hot coals with your bare hands and trying to throw them at the person you're angry at.  Who gets burned first?

> Avoid using "should" and absolutes like "never", 'always", and "every".  Absolutes are hot-button words that can easily shut down the other person's willingness to listen.

> Poke holes of wakefulness into your mindless communication habits.

> What you do not say in a situation is often as important as what you say.

> Listening to your words during stressful discussions is essential to avoid fueling the fire.

> You can align your speech to the principles of what is truthful and what is most kind and helpful.

> Speak  only that which you know yourself, see by yourself, and find by yourself.

> An alert, calm state of mindfulness, achieved through regular practice, begins to permeate every interaction.

> Take the time to express support for someone else's project or work.

> Connection is your true nature, you just have to learn to permit it.

> The precept of Noble Silence is practiced with no radio, no phone, no television, no writing, no reading, no Internet.

> Remember that how you say something is as important as what you say.

> An injury is much sooner forgotten that an insult. - Lord Chesterfield

> Is the non stop talker an admired person?

> Befriend silence is a process of learning to befriend yourself.

> When you get into a conversation with someone, stay away from your own agenda.  Ask a few open-ended questions that begin with "Why?", "What?", "How?" to get the other person talking.

> When in doubt, go for kindness and postpone saying anything difficult.

> When you love in the present moment, you can be aware of your intentions and see their causal relationship with words.

> If the point you want to make is sound and well grounded, there is no need for aggression or annoyance.

> Meditation siphons off the pools of old collected experience, allowing you to *act skillfully* and *compassionately* *in the present*, instead of reacting to the past.  Let go, forgive, and accept.

> The Five Precepts of Buddhism are:

A. Abstain from taking life.
B. Abstain from taking what is not given.
C. Abstain from false speech.
D. Abstain from sexual misconduct.
E. Abstain from taking intoxicants.

> When your speech is kindly, people will be joyful.  When it is polite, you will have many friends.

> When you are truthful, you can be relied upon.  When you refrain from slander or backbiting, you will be trusted.

> You can put an issue in the foreground and the noise in the background.

> Recognize that words are imperfect, so give them limited importance.

> A mindful listener is one who allows the speaker to express his *heart* and *mind* and expound on his ideas without censure.

> Silence remains, inescapably a form of speech. - Susan Sontay.

>  Negative speech creates an environment in which it becomes difficult to do anything positive.  You cannot feel good about yourself when you intentionally hurt someone else.

> You are faced with faced with guilt and remorse when you speak negatively.  Why should any one trust you if you speak harshly?

> *Be mindful and let your speech come from the heart.*

> Sometimes the most skillful speech is Noble Silence.*

> Sitting meditation practice trains your mind to slow down and interrupt the speed of your thought process.

> Whenever your are about to do or say something, ask yourself if the actions or words will result in *well-being* or *harm*?  If well-being then do or say it.  If harm, then do not do or say it.

> Engaging in harsh, abusive, or sarcastic speech keeps others from trusting in or listening to you.  The listener will try to protect himself, avoid the abuse or be equally aggressive.

> When you are truthful you will be trusted.

> *May my words create mutual understanding and love.*

> *Be quite and let your actions speak for you.*

> How to speak to yourself can have a powerful effect on what happens in your life.

> Lower Your Voice

> The act of saying something kind, true, and honest is in itself the reward.

> *Mindful breathing is the first step to mindful communicating because ti relaxes you in body and mind.*

> If you want others to listen and understand you better think about what makes you want to listen.

> *Imagine that all comments are opinions are like drops of water falling into a pound and that ripples represent the signals you send out to those around you.*

> As you connect with yourself, you being, connecting more deeply with other people.  Without the first step, the second step is not possible.

> *Close your lips and say nothing.*

> *Refrain from using speech that is hurtful.*

> The voice is a second face. - Gerad Bauer

> *When you are trying to control others, what you are typically doing is watching somebody else instead of being mindful of your own actions.*

> The reason why we have two ears and one mouth is that we may listen the more and talk less.

> Often, when listening to someone who needs your help, the best thing to do is to remain silent and just listen.

> *Refrain from wrong speech means telling the truth but avoiding useless and frivolous talk.*
 
> Summarizing is a technique that sends the subliminal message, "I am repeating what I think you said, because I really want to understand your viewpoint.

> *Endeavor to make your speech become much simpler, calmer, and more worthy.*

> Do what you say and say what you mean.

> *Mindfulness can help make your conversations deeper, more meaningful, more satisfying.  It's a combination of _mindful speech_ and _deep listening_.*

> Learning to take care of your speech is learning to take care of your *thoughts*, *feelings*, and *mind*.

> Learn to cultivate *loving, kindness, compassion, wisdom, and simplicity* as *these are the seeds from your speech is born.*






-










