=== Today I am Resolved to See Only The Good

_"He brought them out of darkness and the shadow of death, and brake their bands in sunder."_ - PSALM 107:14

_"Sin is an obstruction in the heart; an inability to feel and comprehend all that is noble, true and great, and to take part in the good."_ - The Talmud

    We all wish to be brought out of darkness into the light.  To be free from the bondage of fear, superstition, and want, the mind must be riveted on freedom.  The thought must rise transcendent over bondage.  If we do this, then we are brought from the shadow of darkness into the light of the glorious freedom of God.  The Talmud tells us that if we would be free from sin (mistake) the mind and heart must be open to enlightenment.  Ignorance of the Truth is the great sin or mistake from which spiritual enlightenment alone can give freedom.  But what is spiritual enlightenment other than an increasing capacity consciously to become aware of the Divine presence as peace, joy, and harmony?  If we are to know the Truth that makes us free, we must first recognize the essential nonreality of evil as being a thing within itself; we must equally know the essential absolute reality of good, not only as the Supreme Beneficence, but as the Absolute Power.

    Therefore, today I am resolved to see only the good, and whenever evil, in the form of lack, fear, pain, or uncertainty, presents itself, I shall endeavor instantly to recognize its native nothingness, to know that it is entirely relative.  I shall make every effort to see through this limitation to that which is boundless and free.  I shall proclaim the glad tidings of the freedom of the Kingdom of God in my experience and in the experience of everyone I contact.

    December - Light - 365 Science of Mind - Ernest Holmes


