


=== snippets_from_dreams_your_magic_mirror.adoc

=== Written by Cyric263

=== Date: Fri Jun 20, 2017

=== Book Title: DREAMS - YOUR MAGIC MIRROR 

=== Book Written By Elsie Sechrist

Log 1: A small glimpse into Elsie Sechrist's book, "DREAMS - YOUR MAGIC MIRROR" via Chapter Nine.

Chapter Nine of Elsie's book is titled "Communication with the Dead in Dreams" and although it is just four written pages it reveals that Cayce's readings did reveal a spiritual universe and that we can communicate with this universe via dreams and meditation. Here are just a few snippets to wrap your mind around:

=== Message Snippets - Page 71

1. When we die the subconscious mind replaced the conscious mind and the superconscious replaces the subconscious position.

2. The body is ejected but all else functions properly. 

3. Communication to those who have passed can happen in dreams but many find this difficult grasp.

Cayce...

> Your mother is alive and happy... For there is no death, only a transition from the physical to the spiritual plane.

> Birth into the physical plane is referred to as a new life. Birth into the spiritual is the beginning, also, of a new life or a new experience.

"Does mother try to tell me she is alive and happy... or am I fooling myself?"

Cayce...
> No, you are not fooling yourself, for the soul of your mother liveth and is at peace, and wants you entity to know this.

=== Message Snippets - Page 72

Cayce Quote...
> There is more to life than just living, and death is not the end.  Thoughts and deeds create conditions that must be met; for the soul liveth and is a portion of the Creative Energy. It returns to the Whole, God, yet keeps its own identity as a portion of the Whole.  All then are a part of God, for He is God of all.

> Remember, too, that thoughts are deeds in the mental realm, and they increase or mar the activities of the higher self

Those on the spiritual plane can see the future and when the mind meditates or sleeps it can align with the spiritual plane for communications or attunement.

=== Message Snippets - Page 73

Cayce quote...

> The prayers of the righteous shall save many. Jesus said that where two or three are joined together in one purpose, He was in the midst of them.  The combined prayers of husband and self brought the attunement (ESP) to the spiritual forces in the material world.

> Both are still in the physical plane until the spiritual forces lead them through an ever increasing awareness to the Union with the One Force

=== Message Snippet - Page 74

> The Lesson then: Love those about you in the way that mother did.  Be that person mother would have you be. Mother is still with you, sister, and mother knows! For life includes the life of the spiritual being in the cosmic planes... For the love of the mother has neither disappeared nor passed on, but is present among the living! For God is the God of the living (spiritually alive).  The Savior is the Savior for the Living 243-D

The Question...
Is it our subconscious minds that meet, I in sleep and he in the cosmic (death) plane as a vibratory force meets a radio machine and  causes a sound when the radio is turned on?

Cayce...
> That is an illustration.  Both minds must be in the same attunement or vibration and separated from the physical consciousness; for these are the spiritual consciousness.  Only through an attunement may a message (from a departed one) be received. - 410-10

In conclusion:

Ending with a Cayce reference... 

"In my Father's house there are many mansions" - John 14.2












