



=== spiritual_hinduism.adoc

*Hinduism:* In the 1800s, had philosophers like Merson and Thoreau which were so influenced by Hindu thought that they incorporated concepts like the *Universal Soul* and *Oneness* with the *Divine* into the works.

*Hindu Masters:* Swami Vivekananda, Paramahansa Yogananda, The Mahrishi Mahesh (yogi) -> founder of the Transcendental Meditation and Swami Prabhupada

Hindu has thousands if not millions of Gods, multiple levels of society (castes) and numerous philosophical teachings anad practices including *yoga* and *vendanta*.

Underneath the *unifying* principle of Hindu beleif is that all things, all Gods, all beliefs, all peoples and *all life are One*. Or, as the sacred Vedas, the ancient scriptures of India, put it... _*"Truth is one, the wise call it by many names."*_  Hinduism is one of the most tolerant belief systems, acknowledging and even embracing other religions and GOds as *different pathes to the same end goal* of _enlightenment and oneness with the Divine_.

"If i were asked under which the human mind has most fully developed some of its best gifts, his most deeply pondered on the greatest on the greatest problems of Life and has found solutions, I should point to India." - Max Muller - German Scholar 1823-1900).

Hindus call their tradition of vast and varity unity by it's Sanskrit name: *Santana Dharma*...

*The Eternal Law.*

Hindus believe the following:

1. The Vedas are the sacred scriptures of India.  Oldest recorded religious text in the world.

2. Vedas were revealed to seven saint like sears called rishis during a state of deep meditation.

3. Vedas are a collection of hymns, chants, incanations and rituals.  

They were passed on orally not written until 1,000 B.C.E. - maybe composed 5,000 years before.

Most influential of Vedic text is the *Upanishads* also called *Vedanta* 700 - 300 BCE.  It emphaszed philosophical wisdom over traditional rituals.

4. Upanishads emphasized meditation, pranayama (breathing exercises).

5. Despite Hindu Panthem (330 million Gods) *most Hindus still believe God is One.*

_One Universal God called *Brahman*_

The eternal state of pure being and infinite consciousness.  Without properties, beginning or end.

Westernized groups call Brahman as: *Universal Consciousness*

Each individual has the choice of which form or combinations of forms taht humans can identify with or be their object of worship.

*Om* or *Ohm* or *Aum* is the most sacred matra representing primal energy and vibration of the universe.  Through chanting it one comes in contact with *Universal Consciousness*.

Silence is most important elment of the Om.

Mind that comprehends this has reached highest state of consciousness.

"When I read teh Bhagavad-Gita and reflect about how God craeted this universe everything else seems so superfluous." - Albert Einstain.

t influential Poem: Mahabharata 600BCE + 500ce (4 times as long as the bible) - It contains the Bhagavad Gita - Song of the Lord.

Gita: developed several ideas and raised status of Krishna to the most popular dieties in India.  Yoga - Braham as the impersonal Absolute.

Real KamaSutra written by Indian Sage Vatsyayana between 1st and 6th century CE were *"Aphorisms on Love".

*Brahman* (God) exists in every human and called *Atman*.  The true self that is infinite, unchanging and eternal.  The Hindu saltation *Namaste* means _"I bow to God Within You".

Hindus believe humans are mislead to believe that their true selfs are material bodies.

6. *Samsara:* is a moral order to the Universe, death, rebirth, and reincarnation.

The moral order of the UNiver is called *dharma*. and governed by the Law of Cause and Effect called *karma*.

Every action has a reaction (good or bad).  What goes around comes around.  Negative actiosn generate negative karma, which is accumulated over several lifetimes, obscurnig our ability to recognize our true self.

*Brahmans:* priests, scholars, philosphers (keeprs of knwoledge).

*Kshatrigas:* Kings, politicians, warrriors

*Vaishgas:* merchants, farmers, tradesmen.

*Shudras:* servants and unskilled laborers.

*Untouchables:* didnt rate, unclean...

Oppositin to this system grew.  Buddhism, Jainism, and Sikhism came out of Hinduism.

Gandhi also was against the caste system.

Gandhi renamed "untouchables" to barijan or "Children of God."

It is possible to break free from samsara... (results up to individual).

*Goal of Life is to regain awareness of true self or Atman*

or

*Attain Enlightenment and Reunite with Brahman or Universal Consciousness*

_When this occurs our souls are liberated (moksha) from the cycle of death and rebirth and experience a state of Irvana._

not heaven but...

_Unity between *atman* and *brahman.*_

*--* To extinguish the sense of separateness from God adn the UNiverse. *--*

*Sadhus:* ascetic holy men, whose long matted hair and skeletal bodies appear in many photos are extreme examples of how one burns the karmic debt and realzies God through asceticism... The total denial of body and material world.

* There are many pates to God, Reflecting the idea that many are One, Hinduism, accepts all religions as valid means to God and each person needs approach God in his or oer own way.  

* The most popular systems in the USA are *Vedanta, Yoga, and studing with Gurus or Spiritual Masters.

Vendanta came after Upanishads from which it originates.

Upanishads + Bhagavad Gita

*Vendanta* is concerned with knowledge of Absolute Brahman and relationship of individual souls to it is called *Catman*.

There are several Vendantic Views on this relationship.  The most popular view is called:

*Advaita* - _it says their is no distinction between self and Brahman._

Exemplified in phrase from Upanishads...

*Tat Tuam Asi*

or 

*That THou Art*

Atman, Brahman, and all existence are on in the same.

The goal is to realize the selfs innate divinity and oneness with all existence and to _reunite with the *Absolute* or *Brahman*_ ultimately experiencing Nirvana.

The disciplines that lead to Nirvana are as numerous as individual tastes.  They are called *Yoga*.

*Yoga* means union with brahman.
*bhakti* - love devotion
*Jnana* - wisdom and self analysis
*raja* HathaYog

"Yoga of Food - Melissa graau, PHD.

"Your repeated actions (samskarus) power of habit make grooves in the body mind which are created over time... through repeated action.

"Samskarus create material and energetic conditiosn taht strongly influence your current and future patterns of thought and behavior.

Neurons that fire together wire together

The way you in habit your body day to day is a habit of being.  How you breath, walk, feed yourself are habits of being.

Changin tehse ingrained rhythms of self-relationship is possib.e

Aristotle- "we are what we repeatedly do."  We are nto fixed entities and we are always unfolding and can begin repeating new behavioral patterns.

10 Practices to Unclutter your Soul by Bill Hybels:

1. Energized
2. Organized
3. Control
4. Fulfilled
5. Whole
6. Peaceful
7. Connected
8. Focused
9. Moving On
10. Satisfied.

Welcome new sessions in your life.  Turn Turn Turn... There are Seasons of Life.  Desern what season you are in.... A season is a subplot to the narrative of your overall Life story... not the whole life only a season.

...

"I've learned that people will forget what you said,
People will forget what you did, 
but people will never forget how you made them feel." 
   - Maya Angelou




