
== Spirit Permeates
365 Science of Mind <ernest@holmes>

=== Spirit Permeates My Consciousness and Environment

"It is only as you live affirmatively that you can be happy. Knowing that there is but one Spirit in which you live, move, and have your being, you are to feel this Spirit not only in your consciousness but in your affairs. You are united with all. You are one with the eternal Light Itself. The Presence of Spirit within you blesses everyone you meet, tends to heal everything you touch, brings gladness into the life of everyone you contact. Therefore, you are a blessing to yourself, to humankind, and to the day in which you live.

Say: Today I uncover the perfection within me. In its fullness I reveal the indwelling Presence. I look out upon the world of my affairs, knowing that the Spirit within me makes my way both immediate and easy. I know there is nothing in me that could possibly obstruct or withhold the Divine Circuit of Life and Love, which Good is.

My world dissolves every negative thought or impulse that could throw a shadow over my perfection. Good flows through me to all. Good shines through my thoughts and actions. Good harmonizes my body so that it is revitalized, manifesting perfection in every cell, organ, and function. Good harmonizes my mind so that Love sings joyously in my heart. I am in complete unity with Good."

