
=== Title: "The Innocent Perception Ch3": I. Atonement without Sacrifice

=== Source: Course In Miracles Book

=== Reflecting the Concepts

=== Source Link: https://acimi.com/a-course-in-miracles/text/chapter-3/atonement-without-sacrifice


* "The best defense, as always, is not to attack another's position, but rather to protect the truth."

* "the "evil" past has nothing to do with GOd.  "He did not create it and He does not maintain it. God does not believe in retributioin.  His Mind does not create that way. He does not hold your evil deeds against you.  Is it likel He would hold them against me?"

* A host of errors like God rejected Adam and forced him out of the Garden of Eden.  It is also why you may believe from time to time that I am misdirecting you."

* Sacrifice is a notion totally unknown to God.  It arises soley from fear, and frightened people can be vicious.  Sacrificing in any way is a violation of my injuction that you should be merciful even as your Father in Heaven is merciful... ... Good teachers never terrorize their students.  To terrorize is to attack, and this results in rejection of what the teacher offers.  The result is learning failure.


