

=== Title:  what_kind_of_day_do_you_want.adoc

=== Subject: Snippets And Quotes

=== Source: Course In Miracles, Chapter 30 - The New Beginning

* Moving from dreams of judgement to forgiving dreams and moving out of pain and fear.

* Steps to Let Yourself Be Helped and Getting what you want for the day!

=== Ideas or Thought Rules to Live By

=== Rules for Decisions - Learning To Hear

1. Today I will make no decisions by myself.

Don't judge what you are to do today.

2. Through out the day, tell yourself again. - "Thought, Feeling, Behavior - Cycle"

  1. What kind of day you want.
  2. The feeling yous you would have.
  3. The things you want to happen to you.

* These two procedures will have you be directed without fear!

_*If I make no decisions of myself this is the day that will be given me.*_

4. Times when you judged already say:

_*I have no question.  I forgot what to decide.*_

* This cancels out the terms that you have set, and lets the answer showyou what the question must have really been.


5. Still doesn't work
  _*At least I can decide I do not like what i feel now.*_

6. _*And So I hope I hvae been wrong.*_ (to let yourself be helped).

7. _*I want another way to look at this.  *_

* Now you have changed your mind about the day, and have remembered what you really want.  

* You can not be in conflict when you ask for what you want!!!

8. Say what you want honestly:  _*I want another way to look at this.*_

9. Open Mind: _*Perhaps there is another way to look at this.  What can I lose by asking?*_

* You will not make decisions by yourself, whatever you decide.

* You must agree on what you want before it can occur.

A. "Decisions cause results because they are not made in isolation. 
B. "Decisions made for you and the world.
C. "It will be what you have asked for and reinforce the rule of your adviser in the world."
D. "It needs but two; And as you have received, so must you give."






  
